module.exports = {
  preset: '../../helpers/test/presets/withSnapshotSerializer.js',
  modulePathIgnorePatterns: [
    '<rootDir>/dist/',
    '<rootDir>/fixtures/',
    '<rootDir>/generator-build/',
    '<rootDir>/runtime/',
    '<rootDir>/runtime-dist/',
    '<rootDir>/scripts/',
    '<rootDir>/tests/memory',
    '<rootDir>/tests/functional',
    '<rootDir>/tests/e2e',
    '<rootDir>/src/__tests__/benchmarks/',
    '<rootDir>/src/__tests__/types/.*/test.ts',
    '<rootDir>/src/__tests__/types/.*/test.binary.ts',
    '<rootDir>/src/__tests__/types/.*/test.library.ts',
    '<rootDir>/src/__tests__/integration/happy/not-so-exhaustive-schema/common.ts',
    '<rootDir>/src/__tests__/integration/happy/not-so-exhaustive-schema/generated-dmmf.ts',
    '<rootDir>/src/__tests__/generation/__fixture__',
    '<rootDir>/src/__tests__/integration/happy/not-so-exhaustive-schema-mongo/common.ts',
    '<rootDir>/src/__tests__/integration/happy/not-so-exhaustive-schema-mongo/generated-dmmf.ts',
    '__helpers__/',
    'node_modules/',
    'index.ts',
    'index.d.ts',
    'index.js',
    'index.test-d.ts',
    '.bench.ts',
  ],
  collectCoverageFrom: ['src/**/*.ts', '!**/__tests__/**/*', '!src/**/*.test.ts'],
  testTimeout: 90_000,
  setupFiles: ['./helpers/jestSetup.js'],
  openHandlesTimeout: 10_000,
  prettierPath: '../../node_modules/prettier2',
}
