# Enable/Disable PR comments
comment: false

# About `carryforward: true`
# https://docs.codecov.com/docs/carryforward-flags

flags:
  cli:
    carryforward: true
    paths:
      - packages/cli/
  client:
    carryforward: true
    paths:
      - packages/client/
  debug:
    carryforward: true
    paths:
      - packages/debug/
  engine-core:
    carryforward: true
    paths:
      - packages/engine-core/
  generator-helper:
    carryforward: true
    paths:
      - packages/generator-helper/
  integration-tests:
    carryforward: true
    paths:
      - packages/integration-tests/
  migrate:
    carryforward: true
    paths:
      - packages/migrate/
  internals:
    carryforward: true
    paths:
      - packages/internals/
  instrumentation:
    carryforward: true
    paths:
      - packages/instrumentation/
  get-platform:
    carryforward: true
    paths:
      - packages/get-platform/
  fetch-engine:
    carryforward: true
    paths:
      - packages/fetch-engine/
  engines:
    carryforward: true
    paths:
      - packages/engines/
