# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Never close the issues
daysUntilClose: false

# exempt every other kind of issues expect kind/bug
exemptLabels:
  - kind/discussion
  - kind/docs
  - kind/feature
  - kind/improvement
  - kind/question
  - kind/regression

# Label to use when marking an issue as stale
staleLabel: status/needs-action
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: false
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
# Limit to only `issues`
only: issues
