/**
 * Integration test: introspection of `GENERATED ... AS IDENTITY` columns.
 *
 * An identity column reports no `column_default` at all — Postgres tracks
 * generation via `pg_attribute.attidentity`, not a default expression. The
 * columns query selects `attidentity` and, when it reports either identity
 * variant, the control adapter stamps `resolvedDefault` straight to
 * `autoincrement()` — the same value a contract's `@default(autoincrement())`
 * resolves to. Without this, `db verify` would see the contract-derived side
 * declare a default the introspected side never reports, and flag every
 * identity column drifted forever (TML-3037).
 */
import { PostgresDatabaseSchemaNode } from '@internal/target-postgres/types';
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import {
  createDriver,
  createTestDatabase,
  familyInstance,
  type PostgresControlDriver,
  resetDatabase,
  testTimeout,
} from './fixtures/runner-fixtures';

describe('identity column introspection', { concurrent: false }, () => {
  let database: Awaited<ReturnType<typeof createTestDatabase>>;
  let driver: PostgresControlDriver | undefined;

  beforeAll(async () => {
    database = await createTestDatabase();
  }, testTimeout);

  afterAll(async () => {
    if (database) await database.close();
  }, testTimeout);

  beforeEach(async () => {
    driver = await createDriver(database.connectionString);
    await resetDatabase(driver);
  }, testTimeout);

  afterEach(async () => {
    if (driver) {
      await driver.close();
      driver = undefined;
    }
  }, testTimeout);

  it('GENERATED ALWAYS AS IDENTITY -> no raw default, resolvedDefault:autoincrement()', {
    timeout: testTimeout,
  }, async () => {
    await driver!.query(
      'CREATE TABLE identity_test (id int4 GENERATED ALWAYS AS IDENTITY PRIMARY KEY)',
    );

    const result = await familyInstance.introspect({ driver: driver! });
    PostgresDatabaseSchemaNode.assert(result);
    const col = result.namespaces['public']!.tables['identity_test']?.columns['id'];
    expect(col?.default).toBeUndefined();
    expect(col).toMatchObject({
      resolvedDefault: { kind: 'function', expression: 'autoincrement()' },
    });
  });

  it('GENERATED BY DEFAULT AS IDENTITY -> no raw default, resolvedDefault:autoincrement()', {
    timeout: testTimeout,
  }, async () => {
    await driver!.query(
      'CREATE TABLE identity_test (id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)',
    );

    const result = await familyInstance.introspect({ driver: driver! });
    PostgresDatabaseSchemaNode.assert(result);
    const col = result.namespaces['public']!.tables['identity_test']?.columns['id'];
    expect(col?.default).toBeUndefined();
    expect(col).toMatchObject({
      resolvedDefault: { kind: 'function', expression: 'autoincrement()' },
    });
  });

  it('serial column (control) -> resolvedDefault:autoincrement() via nextval()', {
    timeout: testTimeout,
  }, async () => {
    await driver!.query('CREATE TABLE identity_test (id serial PRIMARY KEY)');

    const result = await familyInstance.introspect({ driver: driver! });
    PostgresDatabaseSchemaNode.assert(result);
    const col = result.namespaces['public']!.tables['identity_test']?.columns['id'];
    expect(col?.default).toMatch(/^nextval\(/);
    expect(col?.resolvedDefault).toEqual({ kind: 'function', expression: 'autoincrement()' });
  });

  it('plain int column (control) -> no default at all', {
    timeout: testTimeout,
  }, async () => {
    await driver!.query('CREATE TABLE identity_test (id int4 PRIMARY KEY, note int4)');

    const result = await familyInstance.introspect({ driver: driver! });
    PostgresDatabaseSchemaNode.assert(result);
    const col = result.namespaces['public']!.tables['identity_test']?.columns['note'];
    expect(col?.default).toBeUndefined();
    expect(col?.resolvedDefault).toBeUndefined();
  });
});
