name: Setup
description: Boilerplate steps needed by most jobs.

inputs:
  node-version:
    description: 'Version of Node.js to use.'
    required: true
  skip-tsc:
    description: 'Skip type checking.'
    required: true
  skip-build:
    description: 'Skip build (Default: false).'
    required: false
    default: 'false'
  engine-hash:
    description: 'Pick up custom built engine from cache'
    required: false

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4.0.0
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        # This makes it possible to publish to npm later
        # The NPM_TOKEN secret needs to be defined in the job
        registry-url: 'https://registry.npmjs.org'

    - run: pnpm install
      shell: bash

    - run: pnpm -r run dev
      if: inputs.skip-tsc == 'true' && inputs.skip-build != 'true'
      shell: bash

    - name: Download custom engines
      id: custom-engine
      uses: actions/cache/restore@v4
      with:
        key: ${{ runner.os }}-engine-${{ inputs.engine-hash }}-${{ github.event.number }}
        path: |
          target/release/schema-engine
          target/release/schema-engine.exe
          target/prisma-schema-wasm
          query-compiler/query-compiler-wasm/pkg
          schema-engine/schema-engine-wasm/pkg

    - name: Set environment variables for custom engine
      if: steps.custom-engine.outputs.cache-hit == 'true'
      run: |
        RELEASE_DIR="$(pwd)/target/release"
        if [ -f "$RELEASE_DIR/schema-engine" ]; then
          echo "PRISMA_SCHEMA_ENGINE_BINARY=$RELEASE_DIR/schema-engine" >> $GITHUB_ENV
        elif [ -f "$RELEASE_DIR/schema-engine.exe" ]; then
          WIN_RELEASE_DIR=$(cygpath -w $RELEASE_DIR)
          echo "PRISMA_SCHEMA_ENGINE_BINARY=$WIN_RELEASE_DIR\\\schema-engine.exe" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Override WASM modules
      if: steps.custom-engine.outputs.cache-hit == 'true'
      shell: bash
      run: |
        ENGINE_PATH="$(pwd)/target"

        mv query-compiler/query-compiler-wasm/pkg "$ENGINE_PATH/query-compiler-wasm"
        mv schema-engine/schema-engine-wasm/pkg "$ENGINE_PATH/schema-engine-wasm"

        if [ "$RUNNER_OS" == "Windows" ]; then
          ENGINE_PATH=$(cygpath -w "$ENGINE_PATH")
        fi

        pnpm update -r "@prisma/prisma-schema-wasm@$ENGINE_PATH/prisma-schema-wasm"
        pnpm update -r "@prisma/query-compiler-wasm@$ENGINE_PATH/query-compiler-wasm"
        pnpm update -r "@prisma/schema-engine-wasm@$ENGINE_PATH/schema-engine-wasm"

    - run: pnpm run build
      if: inputs.skip-tsc == 'false' && inputs.skip-build != 'true'
      shell: bash
