catalog:
  '@antfu/ni': 0.21.12
  '@cloudflare/workers-types': ^4.20250408.0
  '@codspeed/benchmark.js-plugin': 4.0.0
  '@hono/node-server': 1.19.0
  '@inquirer/prompts': 7.3.3
  '@libsql/client': 0.8.1
  '@neondatabase/serverless': 0.10.2
  '@opentelemetry/api': 1.9.0
  '@opentelemetry/context-async-hooks': 2.0.1
  '@planetscale/database': ^1.15.0
  '@prisma/engines-version': 6.18.0-2.ba2627112b75424f26505fb83167ce78db40fc57
  '@prisma/mini-proxy': 0.9.5
  '@prisma/query-compiler-wasm': 6.18.0-2.ba2627112b75424f26505fb83167ce78db40fc57
  '@prisma/query-engine-wasm': 6.18.0-2.ba2627112b75424f26505fb83167ce78db40fc57
  '@prisma/prisma-schema-wasm': 6.18.0-2.ba2627112b75424f26505fb83167ce78db40fc57
  '@prisma/schema-engine-wasm': 6.18.0-2.ba2627112b75424f26505fb83167ce78db40fc57
  '@sindresorhus/slugify': 2.2.1
  '@swc/core': 1.11.5
  '@swc/jest': 0.2.37
  '@swc-node/register': 1.10.9
  '@types/fs-extra': 11.0.4
  '@types/jest': 29.5.14
  '@types/node': 18.19.76
  '@types/mssql': 9.1.8
  '@types/pg': 8.11.11
  '@types/pluralize': 0.0.33
  '@types/resolve': 1.20.6
  '@types/sqlite3': 3.1.11
  arg: 5.0.2
  async-mutex: 0.5.0
  benchmark: 2.1.4
  checkpoint-client: 1.1.33
  chokidar: 4.0.3
  ci-info: 4.2.0
  decimal.js: 10.5.0
  empathic: 2.0.0
  env-paths: 2.2.1
  escape-string-regexp: 5.0.0
  execa: 8.0.1
  fast-glob: 3.3.3
  fp-ts: 2.16.9
  fs-extra: 11.3.0
  fs-jetpack: 5.1.0
  globby: 11.1.0
  indent-string: 4.0.0
  jest: 29.7.0
  jest-junit: 16.0.0
  kleur: 4.1.5
  klona: 2.0.6
  log-update: 6.1.0
  mariadb: 3.4.5
  mock-stdin: 1.0.0
  mssql: ^11.0.1
  new-github-issue-url: 0.2.1
  node-fetch: 3.3.2
  npm-packlist: 5.1.3
  open: 7.4.2
  p-map: 4.0.0
  p-retry: 4.6.2
  package-up: 5.0.0
  pg: ^8.11.3
  pluralize: 8.0.0
  postgres-array: 3.0.4
  resolve: 1.22.10
  strip-indent: 4.0.0
  temp-dir: 2.0.0
  tempy: 1.0.1
  terminal-link: 4.0.0
  ts-pattern: 5.6.2
  ts-toolbelt: 9.6.0
  typescript: 5.4.5
  undici: 7.4.0

onlyBuiltDependencies:
  - '@swc/core'
  - better-sqlite3
  - esbuild
  - sharp
  - sqlite3
  - workerd
  - yarn

packages:
  - 'packages/*'

peerDependencyRules:
  allowedVersions:
    '@octokit/core': '>=3'
