packages:
  - packages/*

onlyBuiltDependencies:
  - '@swc/core'
  - better-sqlite3
  - esbuild
  - sharp
  - sqlite3
  - unrs-resolver
  - workerd
  - yarn

peerDependencyRules:
  allowedVersions:
    '@octokit/core': '>=3'
