name: Create Git Tag
description: Creates an annotated git tag if it does not already exist.
inputs:
  token:
    description: GitHub token with repository permissions.
    required: true
  repository:
    description: Target repository in owner/repo format. Defaults to the current repository.
    required: false
  tag-name:
    description: Tag name to create.
    required: true
  commit-sha:
    description: Commit SHA to tag.
    required: true
  message:
    description: Optional tag message. Defaults to the tag name.
    required: false
runs:
  using: composite
  steps:
    - name: Create tag
      uses: actions/github-script@v7
      env:
        INPUT_REPOSITORY: ${{ inputs.repository }}
        TAG_NAME: ${{ inputs.tag-name }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
        TAG_MESSAGE: ${{ inputs.message }}
      with:
        github-token: ${{ inputs.token }}
        result-encoding: string
        # Docs https://octokit.github.io/rest.js/v20#git-create-tag
        script: |
          const repoInput = process.env.INPUT_REPOSITORY
          let owner
          let repo

          if (repoInput && repoInput.includes('/')) {
            const parts = repoInput.split('/')
            if (parts.length !== 2) {
              core.setFailed(`Invalid repository input: ${repoInput}`)
              return
            }
            ;[owner, repo] = parts
          } else {
            ;({ owner, repo } = context.repo)
          }

          const tagName = process.env.TAG_NAME
          if (!tagName) {
            core.setFailed('Missing tag name input.')
            return
          }

          const commitSha = process.env.COMMIT_SHA
          if (!commitSha) {
            core.setFailed('Missing commit SHA input.')
            return
          }

          const messageEnv = process.env.TAG_MESSAGE
          const message = messageEnv && messageEnv.trim().length > 0 ? messageEnv : tagName

          try {
            await github.rest.git.getRef({
              owner,
              repo,
              ref: `tags/${tagName}`,
            })
            core.info(`Tag ${tagName} already exists on ${owner}/${repo}, skipping.`)
            return
          } catch (error) {
            if (error.status !== 404) {
              throw error
            }
          }

          const tag = await github.rest.git.createTag({
            owner,
            repo,
            tag: tagName,
            message,
            object: commitSha,
            type: 'commit',
          })

          try {
            await github.rest.git.createRef({
              owner,
              repo,
              ref: `refs/tags/${tagName}`,
              sha: tag.data.sha,
            })
          } catch (error) {
            if (error.status === 422 && error.message?.includes('Reference already exists')) {
              core.info(`Tag reference refs/tags/${tagName} already exists on ${owner}/${repo}, skipping.`)
              return
            }
            throw error
          }

          core.info(`Created tag ${tagName} on ${owner}/${repo} at ${commitSha}.`)
