name: Create Git Tag
description: Creates an annotated git tag if it does not already exist.
inputs:
  token:
    description: GitHub token with repository permissions.
    required: true
  repository:
    description: Target repository in owner/repo format. Defaults to the current repository.
    required: false
  tag-name:
    description: Tag name to create.
    required: true
  commit-sha:
    description: Commit SHA to tag.
    required: true
  message:
    description: Optional tag message. Defaults to the tag name.
    required: false
runs:
  using: composite
  steps:
    - name: Create tag
      uses: actions/github-script@v7
      env:
        INPUT_REPOSITORY: ${{ inputs.repository }}
        TAG_NAME: ${{ inputs.tag-name }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
        TAG_MESSAGE: ${{ inputs.message }}
      with:
        github-token: ${{ inputs.token }}
        result-encoding: string
        # Docs https://octokit.github.io/rest.js/v20#git-create-tag
        script: |
          const { join } = await import('node:path')
          const { pathToFileURL } = await import('node:url')
          const scriptPath = join(process.env.GITHUB_WORKSPACE, '.github', 'scripts', 'create-git-tag.mjs')
          const { createGitTag } = await import(pathToFileURL(scriptPath).href)
          await createGitTag({ github, core, context })
