name: Question
description: Use the following template to ask your question about Prisma. Make sure to provide clear and concise details to help others understand and address your concerns effectively.

body:
  - type: markdown
    attributes:
      value: |
        Thanks for raising the questions you have about Prisma, we are happy to help! 🙏 Please follow the sections in the template and provide as much information as possible about your problem, e.g. by [setting the `DEBUG="*"` environment variable](https://www.prisma.io/docs/concepts/components/prisma-client/debugging) and enabling [additional logging output](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/logging) in Prisma Client. 
      label: Question
      description: Provide a clear and concise description of the question you have or problem you want to discuss.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: How to reproduce
      description: If your question is about specific behaviour of Prisma, tell us how to reproduce it.
      value: |
        <!--
        1. Go to '...'
        2. Change '....'
        3. Run '....'
        4. See error
        -->
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: prisma-info
    attributes:
      label: Prisma information
      description: Your Prisma schema, Prisma Client queries, ...
      value: |
        <!-- Do not include your database credentials when sharing your Prisma schema! -->
        ```prisma
        // Add your schema.prisma
        ```

        ```ts
        // Add your code using Prisma Client
        ```
  - type: textarea
    id: environment
    attributes:
      label: Environment & setup
      description: In which environment does the problem occur?
      value: |
        - OS: <!--[e.g. macOS, Windows, Debian, CentOS, ...]-->
        - Database: <!--[PostgreSQL, MySQL, PlanetScale, MariaDB, SQL Server, SQLite, MongoDB or CockroachDB]-->
        - Node.js version: <!--[Run `node -v` to see your Node.js version]-->
  - type: textarea
    id: prisma-version
    attributes:
      label: Prisma Version
      description: Run `prisma -v` to see your Prisma version and paste it between the ´´´
      value: |
        ```

        ```
  