// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ContractModelsMap,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'50aadcf996213451cd2876e3caf50c2752b5b8c9ce1aa55dcae24918518b4ffb'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'9c8aa3114e84ed3b7ea2bd57526d9c2e1bf7c5292be694e9d3801f566fda7ccb'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly TelemetryEvent: {
    readonly id: CodecTypes['pg/int8@1']['output'];
    readonly ingestedAt: CodecTypes['pg/timestamptz@1']['output'];
    readonly installationId: CodecTypes['pg/text@1']['output'];
    readonly version: CodecTypes['pg/text@1']['output'];
    readonly command: CodecTypes['pg/text@1']['output'];
    readonly flags: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
    readonly runtimeName: CodecTypes['pg/text@1']['output'];
    readonly runtimeVersion: CodecTypes['pg/text@1']['output'];
    readonly os: CodecTypes['pg/text@1']['output'];
    readonly arch: CodecTypes['pg/text@1']['output'];
    readonly packageManager: CodecTypes['pg/text@1']['output'] | null;
    readonly databaseTarget: CodecTypes['pg/text@1']['output'] | null;
    readonly tsVersion: CodecTypes['pg/text@1']['output'] | null;
    readonly agent: CodecTypes['pg/text@1']['output'] | null;
    readonly extensions: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
  };
};
export type FieldInputTypes = {
  readonly TelemetryEvent: {
    readonly id: CodecTypes['pg/int8@1']['input'];
    readonly ingestedAt: CodecTypes['pg/timestamptz@1']['input'];
    readonly installationId: CodecTypes['pg/text@1']['input'];
    readonly version: CodecTypes['pg/text@1']['input'];
    readonly command: CodecTypes['pg/text@1']['input'];
    readonly flags: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
    readonly runtimeName: CodecTypes['pg/text@1']['input'];
    readonly runtimeVersion: CodecTypes['pg/text@1']['input'];
    readonly os: CodecTypes['pg/text@1']['input'];
    readonly arch: CodecTypes['pg/text@1']['input'];
    readonly packageManager: CodecTypes['pg/text@1']['input'] | null;
    readonly databaseTarget: CodecTypes['pg/text@1']['input'] | null;
    readonly tsVersion: CodecTypes['pg/text@1']['input'] | null;
    readonly agent: CodecTypes['pg/text@1']['input'] | null;
    readonly extensions: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = Omit<
  ContractType<
    {
      readonly namespaces: {
        readonly public: {
          readonly id: 'public';
          readonly kind: 'postgres-schema';
          readonly tables: {
            readonly telemetry_event: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly ingestedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly installationId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly version: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly command: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly flags: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
                readonly runtimeName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly runtimeVersion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly os: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly arch: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly packageManager: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly databaseTarget: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly tsVersion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly agent: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly extensions: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [{ readonly columns: readonly ['ingestedAt'] }];
              foreignKeys: readonly [];
            };
          };
        };
      };
      readonly storageHash: StorageHash;
    },
    {
      readonly TelemetryEvent: {
        readonly fields: {
          readonly id: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
          };
          readonly ingestedAt: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
          };
          readonly installationId: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly version: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly command: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly flags: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
            readonly many: true;
          };
          readonly runtimeName: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly runtimeVersion: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly os: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly arch: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly packageManager: {
            readonly nullable: true;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly databaseTarget: {
            readonly nullable: true;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly tsVersion: {
            readonly nullable: true;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly agent: {
            readonly nullable: true;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly extensions: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
            readonly many: true;
          };
        };
        readonly relations: Record<string, never>;
        readonly storage: {
          readonly table: 'telemetry_event';
          readonly fields: {
            readonly id: { readonly column: 'id' };
            readonly ingestedAt: { readonly column: 'ingestedAt' };
            readonly installationId: { readonly column: 'installationId' };
            readonly version: { readonly column: 'version' };
            readonly command: { readonly column: 'command' };
            readonly flags: { readonly column: 'flags' };
            readonly runtimeName: { readonly column: 'runtimeName' };
            readonly runtimeVersion: { readonly column: 'runtimeVersion' };
            readonly os: { readonly column: 'os' };
            readonly arch: { readonly column: 'arch' };
            readonly packageManager: { readonly column: 'packageManager' };
            readonly databaseTarget: { readonly column: 'databaseTarget' };
            readonly tsVersion: { readonly column: 'tsVersion' };
            readonly agent: { readonly column: 'agent' };
            readonly extensions: { readonly column: 'extensions' };
          };
        };
      };
    }
  >,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly telemetry_event: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'TelemetryEvent';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly TelemetryEvent: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly ingestedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly installationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly version: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly command: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly flags: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly runtimeName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly runtimeVersion: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly os: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly arch: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly packageManager: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly databaseTarget: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tsVersion: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly agent: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly extensions: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'telemetry_event';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly ingestedAt: { readonly column: 'ingestedAt' };
                readonly installationId: { readonly column: 'installationId' };
                readonly version: { readonly column: 'version' };
                readonly command: { readonly column: 'command' };
                readonly flags: { readonly column: 'flags' };
                readonly runtimeName: { readonly column: 'runtimeName' };
                readonly runtimeVersion: { readonly column: 'runtimeVersion' };
                readonly os: { readonly column: 'os' };
                readonly arch: { readonly column: 'arch' };
                readonly packageManager: { readonly column: 'packageManager' };
                readonly databaseTarget: { readonly column: 'databaseTarget' };
                readonly tsVersion: { readonly column: 'tsVersion' };
                readonly agent: { readonly column: 'agent' };
                readonly extensions: { readonly column: 'extensions' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
export type Models = ContractModelsMap<Contract>;
