/**
 * Generated types for Refract Client (JavaScript version)
 * This file is auto-generated by `npx refract generate`
 *
 * Example schema types for testing the automatic import mechanism
 */

// Module augmentation to inject types into the RefractClient
// Note: In a real scenario, this would be generated from TypeScript
// and the type definitions would be in a .d.ts file

console.log('✅ Refract generated types loaded via module augmentation (JS version)')

// This would typically contain the module augmentation in an associated .d.ts file
// For now, this is just to test if the dynamic import mechanism works
