import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { timeouts } from '@repo/test-utils';
import { describe, expect, it } from 'vitest';
import { type EngineRunResult, runOnEngine } from '../../../../utils/cli-test-helpers';

// Port of prisma/prisma@a6d0155
//   packages/client/tests/functional/relationMode-in-separate-gh-action/tests_m-to-n.ts
//   → isSchemaUsingMap=true (@map/@@map) matrix variants, m:n mandatory (explicit).
//
// GAP TRACKER — the faithful @map m:n schema is not emittable today.
//
// prisma-next #1047 ("Every SQL index is name-identified") hard-errors when an
// index-name prefix exceeds 54 characters (Postgres identifiers cap at 63; the
// wire name appends a 9-character content-hash suffix). The mapped
// explicit join table `CategoriesOnPostsManyToMany_AtAtMap` gets a prisma-next
// auto-generated index over its FK columns whose prefix is
//   CategoriesOnPostsManyToMany_AtAtMap_categoryId_AtMap_idx   (55 chars)
// which exceeds the limit, so emitting any of the four @map variants throws.
//
// Upstream (Prisma) does not name this index — it is generated by Prisma 8 — and
// upstream truncates/hashes long auto-generated index names rather than erroring,
// so there is NO faithful way to author the @map schema to dodge the limit (an
// explicit short `map:` on the index would diverge from the ported schema).
//
// The referential-action behaviour these variants cover is exercised faithfully
// by the four `-nomap` variants (in create/update/delete.test.ts) — @map only
// changes physical names, which never surface through the domain-facing ORM API.
// So the map cells live here as gap trackers rather than in the passing matrix:
//   - `it.fails` runs the real `contract emit` on the faithful @map schema and
//     asserts SUCCESS (exit 0). Today it throws the 54-char error, so the test
//     is an expected-fail; when prisma-next truncates/hashes long index names
//     (Prisma parity) the emit will succeed and the assertion flips green,
//     signalling the gap is closed.
//   - a companion `it` pins that today's failure is specifically the
//     index-name-length error, so a drift to any *other* emit failure surfaces
//     as a real (unexpected) failure instead of silently satisfying `it.fails`.

const MAP_VARIANTS = ['default-map', 'cascade-map', 'noaction-map', 'restrict-map'] as const;

async function emitVariant(variant: (typeof MAP_VARIANTS)[number]): Promise<EngineRunResult> {
  const outputPath = mkdtempSync(join(tmpdir(), 'mton-map-emit-'));
  const testDir = join(import.meta.dirname, '_fixture', variant);
  try {
    return await runOnEngine({ testDir, configPath: join(testDir, 'prisma-next.config.ts') }, [
      'contract',
      'emit',
      '--output-path',
      outputPath,
      '--json',
    ]);
  } finally {
    rmSync(outputPath, { recursive: true, force: true });
  }
}

describe('ports/prisma/functional/relationMode-gh-m-to-n › [emit @map] (index-name-length gap)', () => {
  for (const variant of MAP_VARIANTS) {
    describe(variant, () => {
      it(
        'today fails specifically on the 54-byte index-name-length limit',
        async () => {
          const run = await emitVariant(variant);
          expect(run.exitCode).not.toBe(0);
          expect(run.json.at(-1)).toMatchObject({
            kind: 'result',
            envelope: {
              ok: false,
              error: {
                why: expect.stringContaining(
                  'index prefix "CategoriesOnPostsManyToMany_AtAtMap_categoryId_AtMap_idx" exceeds the 54-byte maximum',
                ),
              },
            },
          });
        },
        timeouts.typeScriptCompilation,
      );

      it.fails(
        'emitting the faithful @map contract succeeds (flips green once prisma-next truncates/hashes long index names)',
        async () => {
          const run = await emitVariant(variant);
          expect(run.exitCode).toBe(0);
          expect(run.presented?.data).toMatchObject({ ok: true });
        },
        timeouts.typeScriptCompilation,
      );
    });
  }
});
