/**
 * Infer -> Emit Round-Trip Fidelity (TML-3037 — the instrument)
 *
 * `contract-infer-workflow.e2e.test.ts` already proves infer -> emit -> verify
 * on a two-column table. This journey runs the same shape against a schema
 * that carries the fidelity gaps TML-3037 tracks: an already-plural
 * back-relation target, a 1:1 FK, a 1:N FK, both `GENERATED ... AS IDENTITY`
 * variants plus a `serial` control column, a GIN index, a `USING hash` index,
 * array/jsonb defaults, a foreign key into a schema outside the introspected
 * scope, two foreign keys between the same table pair (one of them unique),
 * and a self-referencing unique foreign key — the two shapes under which
 * infer prints a *named* singular 1:1 back-relation (`@relation(name: ...)`
 * with no `fields`/`references`), as opposed to the bare, unnamed one a
 * single FK between a pair produces.
 *
 * Each `it()` isolates one defect so a single run reports every defect
 * independently instead of stopping at the first failure. Where an
 * unfixed defect would otherwise block `contract emit` before a later
 * defect gets a chance to run, the PSL is surgically reduced (fixing
 * everything except the one thing under test) so that defect's own error
 * surfaces on its own.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { withClient } from '@prisma-next/test-utils';
import stripAnsi from 'strip-ansi';
import { describe, expect, it } from 'vitest';
import { withTempDir } from '../utils/cli-test-helpers';
import {
  type JourneyContext,
  runContractEmit,
  runContractInfer,
  runDbVerify,
  setupJourney,
  timeouts,
  useDevDatabase,
} from '../utils/journey-test-helpers';

const SEED_SQL = `
  CREATE SCHEMA secure;
  CREATE TABLE secure.owners (
    id int4 PRIMARY KEY
  );

  CREATE TABLE users (
    id int4 GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    balance numeric,
    precise_balance numeric(10,2),
    birth_date date,
    tags text[] NOT NULL DEFAULT '{}'::text[],
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
  );
  CREATE INDEX users_metadata_gin_idx ON users USING gin (metadata);
  CREATE INDEX users_email_lower_idx ON users (lower(email));
  CREATE INDEX users_email_active_idx ON users (email) WHERE (birth_date IS NULL);
  CREATE UNIQUE INDEX users_email_ci_key ON users (lower(email));
  CREATE UNIQUE INDEX users_email_plain_key ON users (email);

  CREATE TABLE sessions (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int4 NOT NULL REFERENCES users(id),
    owner_ref int4 REFERENCES secure.owners(id)
  );

  CREATE TABLE identities (
    id serial PRIMARY KEY,
    user_id int4 NOT NULL UNIQUE REFERENCES users(id),
    provider text NOT NULL
  );
  CREATE INDEX identities_provider_hash_idx ON identities USING hash (provider);

  CREATE TABLE accounts (
    id int4 GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    primary_user_id int4 NOT NULL UNIQUE REFERENCES users(id),
    backup_user_id int4 REFERENCES users(id)
  );

  CREATE TABLE categories (
    id int4 GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    parent_id int4 UNIQUE REFERENCES categories(id)
  );
`;

function readContractPsl(ctx: JourneyContext): string {
  return readFileSync(join(ctx.testDir, 'contract.prisma'), 'utf-8');
}

function writeContractPsl(ctx: JourneyContext, psl: string): void {
  writeFileSync(join(ctx.testDir, 'contract.prisma'), psl, 'utf-8');
}

/** Removes the bare, `@relation`-less 1:1 back-relation field infer prints on `Users`. */
function fixOneToOneBackRelation(psl: string): string {
  return psl.replace(/^\s*identities\s+Identities\?\s*$\n/m, '');
}

/** Strips the non-btree `type:` argument infer prints on both `@@index` attributes. */
function fixIndexTypes(psl: string): string {
  return psl.replace(/,\s*type: "(?:gin|hash)"/g, '');
}

withTempDir(({ createTempDir }) => {
  describe('Journey: Infer -> Emit Round-Trip Fidelity', () => {
    const db = useDevDatabase({
      onReady: (cs) => withClient(cs, (client) => client.query(SEED_SQL)),
    });

    it(
      'back-relation naming — an already-plural child table does not double-pluralize',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        const psl = readContractPsl(ctx);
        expect(
          psl,
          'Users back-relation to the plural "sessions" table is "sessions", not "sessionses"',
        ).toMatch(/\bsessions\s+Sessions\[\]/);
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'the interpreter accepts the 1:1 back-relation infer prints for a unique FK',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        // Isolate the 1:1 back-relation defect: fix the one remaining
        // unrelated emit-blocker (non-btree index types) so any failure here
        // is attributable to the 1:1 back-relation alone.
        const reduced = fixIndexTypes(readContractPsl(ctx));
        writeContractPsl(ctx, reduced);

        const emit = await runContractEmit(ctx);
        expect(
          emit.exitCode,
          `contract emit should accept the bare "identities Identities?" 1:1 back-relation ` +
            `field; instead got:\n${stripAnsi(emit.stderr)}\n${stripAnsi(emit.stdout)}`,
        ).toBe(0);
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'the interpreter accepts a named 1:1 back-relation for two FKs sharing a table pair',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        const psl = readContractPsl(ctx);
        // `accounts` has two FKs to `users` (`primary_user_id` is unique,
        // `backup_user_id` isn't), so infer names both relations to
        // disambiguate and prints the 1:1 back side on Users as a singular
        // field carrying only a relation name — no fields/references — a
        // distinct shape from the unnamed singular back-relation a
        // single-FK table pair produces.
        expect(psl, 'Users carries a named singular back-relation to Accounts').toMatch(
          /\w+\s+Accounts\?\s+@relation\(name: "[^"]+"\)\s*$/m,
        );

        // Isolate the named-back-relation defect: fix the one remaining
        // unrelated emit-blocker (non-btree index types).
        const reduced = fixIndexTypes(psl);
        writeContractPsl(ctx, reduced);

        const emit = await runContractEmit(ctx);
        expect(
          emit.exitCode,
          'contract emit should accept the named singular 1:1 back-relation field on Users; ' +
            `instead got:\n${stripAnsi(emit.stderr)}\n${stripAnsi(emit.stdout)}`,
        ).toBe(0);
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'the interpreter accepts a named 1:1 back-relation for a self-referencing unique FK',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        const psl = readContractPsl(ctx);
        // `categories.parent_id` is a unique, self-referencing FK. A
        // self-relation always needs a name to disambiguate its two sides, so
        // infer prints the 1:1 back side as a singular `Categories?` field
        // carrying only a relation name, same as the two-FK case above.
        expect(psl, 'Categories carries a named singular self-referencing back-relation').toMatch(
          /\w+\s+Categories\?\s+@relation\(name: "[^"]+"\)\s*$/m,
        );

        const reduced = fixIndexTypes(psl);
        writeContractPsl(ctx, reduced);

        const emit = await runContractEmit(ctx);
        expect(
          emit.exitCode,
          'contract emit should accept the named singular self-referencing 1:1 back-relation ' +
            `field on Categories; instead got:\n${stripAnsi(emit.stderr)}\n${stripAnsi(emit.stdout)}`,
        ).toBe(0);
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'infer prints the empty-array default on tags as a PSL literal list, and it round-trips clean',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        const psl = readContractPsl(ctx);
        expect(psl, 'Users.tags carries a PSL literal-list default, not dbgenerated').toMatch(
          /tags\s+String\[\]\s+@default\(\[\]\)/,
        );

        // Isolate the list-default defect: fix the one remaining unrelated
        // emit-blocker (1:1 back-relation). The gin/hash index types are left
        // exactly as infer printed them — postgres already registers those
        // access methods (TML-3037) — so verify below also proves that fix
        // stays clean alongside this one.
        const reduced = fixOneToOneBackRelation(psl);
        writeContractPsl(ctx, reduced);

        const emit = await runContractEmit(ctx);
        expect(
          emit.exitCode,
          'contract emit should accept @default([]) on Users.tags; ' +
            `instead got:\n${stripAnsi(emit.stderr)}\n${stripAnsi(emit.stdout)}`,
        ).toBe(0);

        const verify = await runDbVerify(ctx, ['--schema-only']);
        expect(
          verify.exitCode,
          `db verify --schema-only should be clean for Users.tags; instead got:\n${stripAnsi(verify.stderr)}\n${stripAnsi(verify.stdout)}`,
        ).toBe(0);
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'postgres registers the gin and hash index types infer already prints',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        // Isolate the index-type defect: fix the one remaining unrelated
        // emit-blocker (1:1 back-relation).
        const reduced = fixOneToOneBackRelation(readContractPsl(ctx));
        writeContractPsl(ctx, reduced);

        const emit = await runContractEmit(ctx);
        expect(
          emit.exitCode,
          `contract emit should accept @@index(..., type: "gin"/"hash"); instead got:\n` +
            `${stripAnsi(emit.stderr)}\n${stripAnsi(emit.stdout)}`,
        ).toBe(0);
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'a foreign key outside the introspected schema surfaces an explanatory comment',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        const psl = readContractPsl(ctx);
        // sessions.owner_ref points at secure.owners, outside the introspected
        // `public` schema — the scalar column must survive...
        expect(psl, 'dangling FK keeps its scalar column').toContain('ownerRef');
        // ...and the model must explain why the relation is missing, the same
        // way infer already documents a table with no primary key.
        expect(psl, 'Sessions documents the dropped cross-schema relation with a comment').toMatch(
          /\/\/[^\n]*\nmodel Sessions \{/,
        );
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'identity columns (both GENERATED variants) round-trip as autoincrement(); serial keeps working',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        const psl = readContractPsl(ctx);
        expect(psl, 'serial column already carries autoincrement() (control)').toMatch(
          /id\s+Int\s+@id\(map: "identities_pkey"\)\s+@default\(autoincrement\(\)\)/,
        );
        expect(psl, 'GENERATED ALWAYS AS IDENTITY (users.id) carries autoincrement()').toMatch(
          /id\s+Int\s+@id\(map: "users_pkey"\)\s+@default\(autoincrement\(\)\)/,
        );
        expect(
          psl,
          'GENERATED BY DEFAULT AS IDENTITY (sessions.id) carries autoincrement()',
        ).toMatch(/id\s+Int\s+@id\(map: "sessions_pkey"\)\s+@default\(autoincrement\(\)\)/);
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'a jsonb literal default round-trips clean through db verify --schema-only',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        // Fix the one remaining unrelated emit-blocker (1:1 back-relation) so
        // emit succeeds and verify can run. The gin/hash indexes and the tags
        // list default are left exactly as infer printed them — postgres now
        // registers those access methods and infer now prints a literal-list
        // default (TML-3037), so they emit and round-trip clean against the
        // live gin/hash indexes and the live tags default, proving those
        // fixes too. Only the jsonb default on Users.metadata is left broken,
        // which is what this test is for.
        const reduced = fixOneToOneBackRelation(readContractPsl(ctx));
        writeContractPsl(ctx, reduced);

        const emit = await runContractEmit(ctx);
        expect(emit.exitCode, `contract emit\n${stripAnsi(emit.stderr)}`).toBe(0);

        const verify = await runDbVerify(ctx, ['--schema-only']);
        expect(
          verify.exitCode,
          `db verify --schema-only should be clean for Users.metadata; instead got:\n${stripAnsi(verify.stderr)}\n${stripAnsi(verify.stdout)}`,
        ).toBe(0);
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'an expression index infers with expression: and map:, body as the live reprint',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });
        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);
        expect(readContractPsl(ctx)).toContain(
          '@@index(expression: "lower(email)", map: "users_email_lower_idx")',
        );
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'a partial index infers with its where: predicate verbatim',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });
        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);
        expect(readContractPsl(ctx)).toContain(
          '@@index([email], map: "users_email_active_idx", where: "(birth_date IS NULL)")',
        );
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'a unique expression index infers with unique: true instead of being dropped',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });
        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);
        const psl = readContractPsl(ctx);
        expect(psl).toContain(
          '@@index(expression: "lower(email)", map: "users_email_ci_key", unique: true)',
        );
        expect(psl).toContain('@@index([email], map: "users_email_plain_key", unique: true)');
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'full round trip — infer -> emit -> db verify --schema-only, no hand-editing',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        const emit = await runContractEmit(ctx);
        expect(
          emit.exitCode,
          `contract emit (unmodified inferred PSL)\n${stripAnsi(emit.stderr)}\n${stripAnsi(emit.stdout)}`,
        ).toBe(0);

        const verify = await runDbVerify(ctx, ['--schema-only']);
        expect(
          verify.exitCode,
          `db verify --schema-only\n${stripAnsi(verify.stderr)}\n${stripAnsi(verify.stdout)}`,
        ).toBe(0);
      },
      timeouts.spinUpPpgDev,
    );
  });

  describe('Journey: 1:1 detection for FKs enforced by a bare CREATE UNIQUE INDEX', () => {
    // A 1:1 enforced by a plain `CREATE UNIQUE INDEX` (no UNIQUE constraint
    // object) must infer a singular back-relation, but only when the index is
    // total: a partial unique index does not guarantee at-most-one child per
    // parent, and an expression unique index never introspects a usable
    // column set at all.
    //
    // No `contract emit` here: a bare unique index has no PSL representation,
    // so the interpreter rejects the inferred singular back-relation with
    // PSL_NON_UNIQUE_BACKRELATION — a known gap tracked under TML-3086.
    const db = useDevDatabase({
      onReady: (cs) =>
        withClient(cs, (client) =>
          client.query(`
            CREATE TABLE users (
              id int4 PRIMARY KEY
            );

            CREATE TABLE profiles (
              id int4 PRIMARY KEY,
              user_id int4 NOT NULL REFERENCES users(id)
            );
            CREATE UNIQUE INDEX profiles_user_id_idx ON profiles (user_id);

            CREATE TABLE drafts (
              id int4 PRIMARY KEY,
              user_id int4 NOT NULL REFERENCES users(id),
              archived boolean NOT NULL DEFAULT false
            );
            CREATE UNIQUE INDEX drafts_active_user_idx ON drafts (user_id) WHERE NOT archived;

            CREATE TABLE handles (
              id int4 PRIMARY KEY,
              user_id int4 NOT NULL REFERENCES users(id),
              name text NOT NULL
            );
            CREATE UNIQUE INDEX handles_user_lower_name_idx ON handles (user_id, lower(name));
          `),
        ),
    });

    it(
      'a total unique index infers a singular back-relation; partial and expression indexes stay lists',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        const psl = readContractPsl(ctx);
        expect(psl, 'total unique index on profiles.user_id makes the back-relation 1:1').toMatch(
          /\bprofiles\s+Profiles\?/,
        );
        expect(psl, 'partial unique index on drafts.user_id keeps a list back-relation').toMatch(
          /\bdrafts\s+Drafts\[\]/,
        );
        expect(psl, 'expression unique index on handles keeps a list back-relation').toMatch(
          /\bhandles\s+Handles\[\]/,
        );
      },
      timeouts.spinUpPpgDev,
    );
  });
});
