# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
name: Bug report
description: Report a bug in Prisma ORM
labels: ['kind/bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! 🙏

        To help us address your issue as quickly as possible, please fill out all relevant sections in this template.

        The **most important** thing you can do is include a minimal reproduction of the issue.

        Easy ways to create a reproduction:
        - Create a CodeSandbox ([here are templates](https://codesandbox.io/examples/package/prisma))
        - A **GitHub repository** we can clone
        - As a last resort, detailed step-by-step instructions (this makes debugging harder for us)

        We receive a _lot_ of GitHub issues. **Bug reports without a reproduction might not be investigated.**

        💡 If you're trying to ask a question rather than file a bug report, try a GitHub Discussion instead or join our [Discord server](https://discord.com/invite/prisma-937751382725886062).
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear and concise description of the problem.
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - '🚨 Critical: Data loss, app crash, security issue'
        - '⚠️ Major: Breaks core functionality (e.g., migrations fail)'
        - '🔹 Minor: Unexpected behavior, but does not block development'
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: |
        A **minimal reproduction** is required. Provide a CodeSandbox link, GitHub repository, or detailed steps.

        **CodeSandbox template:** [https://codesandbox.io/examples/package/prisma](https://codesandbox.io/examples/package/prisma)

        **If you cannot provide a reproduction, explain why.**
      value: |
        <!-- Link to CodeSandbox, GitHub repo, or step-by-step instructions -->
    validations:
      required: true

  - type: textarea
    id: expected-actual
    attributes:
      label: Expected vs. Actual Behavior
      description: What did you expect to happen, and what actually happened?
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      description: How often does this issue occur?
      options:
        - 'Consistently reproducible'
        - 'Intermittent / Random'
        - 'Happened once'
    validations:
      required: true

  - type: dropdown
    id: environment-type
    attributes:
      label: Does this occur in development or production?
      description: Where does this issue happen?
      options:
        - 'Only in development (e.g., CLI tools, migrations, Prisma Studio)'
        - 'Only in production (e.g., query engine, generated client)'
        - 'Both development and production'
    validations:
      required: true

  - type: textarea
    id: regression
    attributes:
      label: Is this a regression?
      description: Did this work in a previous Prisma version? If so, which version was the last known working one?
      value: |
        <!-- e.g., "Yes, last worked in Prisma 5.1.0, broke in 5.2.0" -->
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Is there a known workaround? If so, describe it.
      value: |
        <!-- e.g., "Downgrading to Prisma 5.1.0 fixes it" or "No workaround found" -->
    validations:
      required: true

  - type: textarea
    id: prisma-info
    attributes:
      label: Prisma Schema & Queries
      description: |
        Provide relevant parts of your **Prisma schema** and **Prisma Client queries**.

        ⚠️ **Do NOT include database credentials!**
      value: |
        ```prisma
        // Add relevant schema.prisma snippet
        ```
        ```ts
        // Add relevant Prisma Client query
        ```
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs & Debug Info
      description: |
        - Run your query with `DEBUG="*"` and paste the output.
        - If relevant, include database logs.
      value: |
        ```
        // Debug logs here
        ```
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment & Setup
      description: |
        Specify the environment details where the issue occurs.
      value: |
        - **OS:** <!-- macOS, Windows, Debian, CentOS, etc. -->
        - **Database:** <!-- PostgreSQL, MySQL, PlanetScale, etc. -->
        - **Node.js version:** <!-- Run `node -v` -->
    validations:
      required: true

  - type: textarea
    id: prisma-version
    attributes:
      label: Prisma Version
      description: Run `prisma -v` and paste the output.
      value: |
        ```
        // Prisma version output
        ```
    validations:
      required: true
