name: Bug report
description: Create a bug report to help us improve Prisma
labels: "kind/bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve Prisma! 🙏 Please follow the sections in the template and provide as much information as possible about your problem, e.g. by setting the `DEBUG="*"` environment variable and enabling additional logging output in Prisma Client.
        Learn more about writing proper bug reports here: https://pris.ly/d/bug-reports
  - type: textarea
    attributes:
      label: Bug description
      value: |
        <!-- A clear and concise description of what the bug is. -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to reproduce
      value: |
        <!--
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Change '....'
        3. Run '....'
        4. See error
        -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      value: |
        <!-- A clear and concise description of what you expected to happen. -->
  - type: textarea
    attributes:
      label: Prisma information
      value: |
        <!-- Your Prisma schema, Prisma Client queries, ...
        Do not include your database credentials when sharing your Prisma schema! -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment & setup
      value: |
        <!-- In which environment does the problem occur -->
        - OS: <!--[e.g. Mac OS, Windows, Debian, CentOS, ...]-->
        - Database: <!--[PostgreSQL, MySQL, MariaDB or SQLite]-->
        - Node.js version: <!--[Run `node -v` to see your Node.js version]-->
        - Prisma version:
        <!--[Run `prisma -v` to see your Prisma version and paste it between the ´´´]-->
        ```

        ```
    validations:
      required: true