export { defaultConfig } from './defaultConfig'
export { defaultTestConfig } from './defaultTestConfig'
export { defineConfig } from './defineConfig'
export { type ConfigFromFile, loadConfigFromFile, type LoadConfigFromFileError } from './loadConfigFromFile'
export type { PrismaConfig, PrismaConfigInternal } from './PrismaConfig'
