export const dmmf = {
  enums: [
    {
      name: 'Tree',
      values: ['ARBORVITAE', 'YELLOWBIRCH', 'BLACKASH', 'DOUGLASFIR', 'OAK'],
      dbName: null,
    },
    {
      name: 'Permission',
      values: ['ADMIN', 'USER', 'OWNER', 'COLLABORATOR'],
      dbName: null,
    },
  ],
  models: [
    {
      name: 'User',
      isEmbedded: false,
      dbName: null,
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          dbName: null,
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: true,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'name',
          kind: 'scalar',
          dbName: null,
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'email',
          kind: 'scalar',
          dbName: null,
          isList: false,
          isRequired: true,
          isUnique: true,
          isId: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'status',
          kind: 'scalar',
          dbName: null,
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'nicknames',
          kind: 'scalar',
          dbName: null,
          isList: true,
          isRequired: false,
          isUnique: false,
          isId: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'permissions',
          kind: 'enum',
          dbName: null,
          isList: true,
          isRequired: false,
          isUnique: false,
          isId: false,
          type: 'Permission',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'favoriteTree',
          kind: 'enum',
          dbName: null,
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          type: 'Tree',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'location',
          kind: 'object',
          dbName: null,
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          type: 'Location',
          relationName: 'LocationToUser',
          relationToFields: ['id'],
          relationOnDelete: 'NONE',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'posts',
          kind: 'object',
          dbName: null,
          isList: true,
          isRequired: false,
          isUnique: false,
          isId: false,
          type: 'Post',
          relationName: 'PostToUser',
          relationToFields: [],
          relationOnDelete: 'NONE',
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      isGenerated: false,
    },
    {
      name: 'Post',
      isEmbedded: false,
      dbName: null,
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          dbName: null,
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: true,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'name',
          kind: 'scalar',
          dbName: null,
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'email',
          kind: 'scalar',
          dbName: null,
          isList: false,
          isRequired: true,
          isUnique: true,
          isId: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'user',
          kind: 'object',
          dbName: null,
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          type: 'User',
          relationName: 'PostToUser',
          relationToFields: ['id'],
          relationOnDelete: 'NONE',
          isGenerated: true,
          isUpdatedAt: false,
        },
      ],
      isGenerated: false,
    },
    {
      name: 'Location',
      isEmbedded: false,
      dbName: null,
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          dbName: null,
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: true,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'city',
          kind: 'scalar',
          dbName: null,
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'user',
          kind: 'object',
          dbName: null,
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          type: 'User',
          relationName: 'LocationToUser',
          relationToFields: [],
          relationOnDelete: 'NONE',
          isGenerated: true,
          isUpdatedAt: false,
        },
      ],
      isGenerated: false,
    },
  ],
}
