import { generateTestClient } from '../../../utils/getTestClient'

let prisma

describe('someemptytest', () => {
  // with const { PrismaClient } = require('./node_modules/@prisma/client')
  // PRISMA_CLIENT_ENGINE_TYPE=library node ./node_modules/jest/bin/jest.js --runInBand --logHeapUsage --no-cache empty-tests-jest

  //  PASS  src/__tests__/integration/empty-tests-jest/test142.ts (8.612 s, 266 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test78.ts (238 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test113.ts (262 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test29.ts (292 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test127.ts (263 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test137.ts (277 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test103.ts (305 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test39.ts (5.07 s, 284 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test68.ts (298 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test48.ts (325 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test19.ts (353 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test123.ts (380 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test117.ts (348 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test146.ts (376 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test107.ts (313 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test133.ts (322 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test58.ts (336 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test49.ts (364 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test122.ts (391 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test18.ts (418 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test116.ts (372 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test147.ts (400 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test106.ts (358 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test132.ts (367 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test59.ts (405 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test79.ts (413 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test143.ts (443 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test28.ts (470 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test112.ts (498 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test126.ts (445 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test136.ts (472 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test38.ts (391 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test102.ts (400 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test69.ts (416 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test72.ts (445 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test148.ts (474 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test119.ts (502 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test23.ts (454 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test81.ts (482 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test17.ts (511 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test46.ts (438 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test4.ts (447 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test56.ts (466 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test91.ts (495 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test109.ts (524 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test33.ts (551 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test62.ts (579 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test42.ts (507 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test13.ts (535 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test129.ts (486 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test27.ts (495 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test76.ts (508 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test85.ts (536 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test66.ts (563 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test95.ts (590 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test37.ts (618 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test139.ts (557 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test52.ts (584 MB heap size)

  // without const { PrismaClient } = require('./node_modules/@prisma/client')
  //   PRISMA_CLIENT_ENGINE_TYPE=library node ./node_modules/jest/bin/jest.js --runInBand --logHeapUsage --no-cache empty-tests-jest
  //  PASS  src/__tests__/integration/empty-tests-jest/test42.ts (8.337 s, 254 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test142.ts (221 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test78.ts (232 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test113.ts (264 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test29.ts (281 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test127.ts (251 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test137.ts (268 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test103.ts (299 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test39.ts (233 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test68.ts (237 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test48.ts (269 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test19.ts (237 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test123.ts (242 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test117.ts (274 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test146.ts (287 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test107.ts (316 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test133.ts (289 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test58.ts (302 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test49.ts (332 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test122.ts (293 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test18.ts (323 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test116.ts (233 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test147.ts (239 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test106.ts (271 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test132.ts (233 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test59.ts (239 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test79.ts (270 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test143.ts (284 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test28.ts (256 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test112.ts (284 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test126.ts (298 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test136.ts (235 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test38.ts (242 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test102.ts (272 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test69.ts (234 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test148.ts (239 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test72.ts (271 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test119.ts (285 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test23.ts (313 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test81.ts (269 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test17.ts (300 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test4.ts (314 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test46.ts (292 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test56.ts (323 MB heap size)
  //  PASS  src/__tests__/integration/empty-tests-jest/test91.ts (236 MB heap size)
  beforeAll(async () => {
    await generateTestClient()

    // If we uncomment the next line (require) we get a memory leak
    const { PrismaClient } = require('./node_modules/@prisma/client')

    // prisma = new PrismaClient()
  })

  // Trying to force gc in afterAll doesn't change heap size increasing
  // afterAll(async () => {
  //   // force garbage collection
  //   // requires flag: node --expose-gc
  //   global.gc()
  // })

  test('something', async () => {
    // empty
  })
})
