// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'34dd5176d953c101467355b72fd2adf3e49c97bf13d8198dcc0dafec4d6341ce'>;
export type ExecutionHash =
  ExecutionHashBase<'07bf8bd20b4ab4505cc0a5908a26eb3426e28c15e4876cf38ab0918b9820c405'>;
export type ProfileHash =
  ProfileHashBase<'1a8dbe044289f30a1de958fe800cc5a8378b285d2e126a8c44b58864bac2c18e'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly account: {
    readonly id: Char<36>;
    readonly email: CodecTypes['pg/text@1']['output'];
    readonly name: CodecTypes['pg/text@1']['output'] | null;
    readonly phone: CodecTypes['pg/text@1']['output'] | null;
    readonly avatar: CodecTypes['pg/text@1']['output'] | null;
    readonly bio: CodecTypes['pg/text@1']['output'] | null;
    readonly locale: CodecTypes['pg/text@1']['output'] | null;
    readonly verified: CodecTypes['pg/bool@1']['output'];
  };
  readonly widget: { readonly id: Char<36>; readonly value: CodecTypes['pg/text@1']['output'] };
};
export type FieldInputTypes = {
  readonly account: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly email: CodecTypes['pg/text@1']['input'];
    readonly name: CodecTypes['pg/text@1']['input'] | null;
    readonly phone: CodecTypes['pg/text@1']['input'] | null;
    readonly avatar: CodecTypes['pg/text@1']['input'] | null;
    readonly bio: CodecTypes['pg/text@1']['input'] | null;
    readonly locale: CodecTypes['pg/text@1']['input'] | null;
    readonly verified: CodecTypes['pg/bool@1']['input'];
  };
  readonly widget: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly value: CodecTypes['pg/text@1']['input'];
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = Omit<
  ContractType<
    {
      readonly namespaces: {
        readonly __unbound__: {
          readonly id: '__unbound__';
          readonly kind: 'postgres-schema';
          readonly tables: {
            readonly account: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly phone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly avatar: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly bio: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly locale: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly verified: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly widget: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly value: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
      readonly storageHash: StorageHash;
    },
    {
      readonly account: {
        readonly fields: {
          readonly id: {
            readonly nullable: false;
            readonly type: {
              readonly kind: 'scalar';
              readonly codecId: 'sql/char@1';
              readonly typeParams: { readonly length: 36 };
            };
          };
          readonly email: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly name: {
            readonly nullable: true;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly phone: {
            readonly nullable: true;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly avatar: {
            readonly nullable: true;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly bio: {
            readonly nullable: true;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly locale: {
            readonly nullable: true;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly verified: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
          };
        };
        readonly relations: Record<string, never>;
        readonly storage: {
          readonly table: 'account';
          readonly fields: {
            readonly id: { readonly column: 'id' };
            readonly email: { readonly column: 'email' };
            readonly name: { readonly column: 'name' };
            readonly phone: { readonly column: 'phone' };
            readonly avatar: { readonly column: 'avatar' };
            readonly bio: { readonly column: 'bio' };
            readonly locale: { readonly column: 'locale' };
            readonly verified: { readonly column: 'verified' };
          };
        };
      };
      readonly widget: {
        readonly fields: {
          readonly id: {
            readonly nullable: false;
            readonly type: {
              readonly kind: 'scalar';
              readonly codecId: 'sql/char@1';
              readonly typeParams: { readonly length: 36 };
            };
          };
          readonly value: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
        };
        readonly relations: Record<string, never>;
        readonly storage: {
          readonly table: 'widget';
          readonly fields: {
            readonly id: { readonly column: 'id' };
            readonly value: { readonly column: 'value' };
          };
        };
      };
    }
  >,
  'roots'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly account: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'account';
    };
    readonly widget: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'widget' };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: { readonly table: 'account'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: { readonly table: 'widget'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
export type Models = Contract['models'];
