// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma-next/target-postgres/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'f820815b9b982ebb9d5f80a2de1a7c0f2a5b16c921a8348fce13d028cf99402a'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly PostOneToMany: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly authorId: CodecTypes['pg/text@1']['output'];
    };
    readonly PostOptionalOneToMany: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly authorId: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly UserOneToMany: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly enabled: CodecTypes['pg/bool@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly PostOneToMany: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly authorId: CodecTypes['pg/text@1']['input'];
    };
    readonly PostOptionalOneToMany: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly authorId: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly UserOneToMany: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly enabled: CodecTypes['pg/bool@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly PostOneToMany_AtAtMap: {
      readonly authorId_AtMap: CodecTypes['pg/text@1']['output'];
      readonly id_AtMap: CodecTypes['pg/text@1']['output'];
    };
    readonly PostOptionalOneToMany_AtAtMap: {
      readonly authorId_AtMap: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
    };
    readonly UserOneToMany_AtAtMap: {
      readonly enabledAtMap: CodecTypes['pg/bool@1']['output'] | null;
      readonly id_AtMap: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly PostOneToMany_AtAtMap: {
      readonly authorId_AtMap: CodecTypes['pg/text@1']['input'];
      readonly id_AtMap: CodecTypes['pg/text@1']['input'];
    };
    readonly PostOptionalOneToMany_AtAtMap: {
      readonly authorId_AtMap: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
    };
    readonly UserOneToMany_AtAtMap: {
      readonly enabledAtMap: CodecTypes['pg/bool@1']['input'] | null;
      readonly id_AtMap: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly PostOneToMany_AtAtMap: {
              columns: {
                readonly id_AtMap: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly authorId_AtMap: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id_AtMap'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly columns: readonly ['authorId_AtMap'];
                  readonly name: 'PostOneToMany_AtAtMap_authorId_AtMap_idx';
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'PostOneToMany_AtAtMap';
                    readonly columns: readonly ['authorId_AtMap'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'UserOneToMany_AtAtMap';
                    readonly columns: readonly ['id_AtMap'];
                  };
                },
              ];
            };
            readonly PostOptionalOneToMany_AtAtMap: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly authorId_AtMap: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly columns: readonly ['authorId_AtMap'];
                  readonly name: 'PostOptionalOneToMany_AtAtMap_authorId_AtMap_idx';
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'PostOptionalOneToMany_AtAtMap';
                    readonly columns: readonly ['authorId_AtMap'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'UserOneToMany_AtAtMap';
                    readonly columns: readonly ['id_AtMap'];
                  };
                },
              ];
            };
            readonly UserOneToMany_AtAtMap: {
              columns: {
                readonly id_AtMap: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly enabledAtMap: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id_AtMap'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly UserOneToMany_AtAtMap: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'UserOneToMany';
    };
    readonly PostOneToMany_AtAtMap: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'PostOneToMany';
    };
    readonly PostOptionalOneToMany_AtAtMap: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'PostOptionalOneToMany';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly PostOneToMany: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly authorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly author: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'UserOneToMany';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['authorId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'PostOneToMany_AtAtMap';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id_AtMap' };
                readonly authorId: { readonly column: 'authorId_AtMap' };
              };
            };
          };
          readonly PostOptionalOneToMany: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly authorId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly author: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'UserOneToMany';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['authorId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'PostOptionalOneToMany_AtAtMap';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly authorId: { readonly column: 'authorId_AtMap' };
              };
            };
          };
          readonly UserOneToMany: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly enabled: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly postOptionals: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'PostOptionalOneToMany';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['authorId'];
                };
              };
              readonly posts: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'PostOneToMany';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['authorId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'UserOneToMany_AtAtMap';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id_AtMap' };
                readonly enabled: { readonly column: 'enabledAtMap' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
