export { getNodeAPIName } from './getNodeAPIName'
export { getos, getPlatform, getPlatformWithOSResult } from './getPlatform'
export { isNodeAPISupported } from './isNodeAPISupported'
export { type Platform, platforms } from './platforms'
export * from './test-utils'
