export { assertNodeAPISupported } from './assertNodeAPISupported'
export { getNodeAPIName } from './getNodeAPIName'
export type { PlatformWithOSResult } from './getPlatform'
export { getos, getPlatform, getPlatformWithOSResult } from './getPlatform'
export { link } from './link'
export { type Platform, platforms } from './platforms'
export * from './test-utils'
