// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as MongoCodecTypes, Vector } from '@prisma/orm-mongo/adapter/codec-types';

import type {
  MongoCollection,
  MongoContractWithTypeMaps,
  MongoTypeMaps,
} from '@prisma/orm-mongo/family-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-mongo/contract/types';

export type StorageHash =
  StorageHashBase<'d264cabd6a02546054a776ed3c04438b9a22989f406c49f5590f7f2101156eb0'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'251b3ce23f6c9f561892e7c1af9d2cc941a13d64ba1aa7226b90036b09568cc3'>;

export type CodecTypes = MongoCodecTypes;

export type AddressOutput = {
  readonly street: CodecTypes['mongo/string@1']['output'];
  readonly city: CodecTypes['mongo/string@1']['output'];
  readonly zip: CodecTypes['mongo/string@1']['output'] | null;
  readonly country: CodecTypes['mongo/string@1']['output'];
};
export type AddressInput = {
  readonly street: CodecTypes['mongo/string@1']['input'];
  readonly city: CodecTypes['mongo/string@1']['input'];
  readonly zip: CodecTypes['mongo/string@1']['input'] | null;
  readonly country: CodecTypes['mongo/string@1']['input'];
};
export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Article: { readonly summary: CodecTypes['mongo/string@1']['output'] };
    readonly Post: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly title: CodecTypes['mongo/string@1']['output'];
      readonly content: CodecTypes['mongo/string@1']['output'];
      readonly kind: CodecTypes['mongo/string@1']['output'];
      readonly authorId: CodecTypes['mongo/objectId@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly Tutorial: {
      readonly difficulty: CodecTypes['mongo/string@1']['output'];
      readonly duration: CodecTypes['mongo/int32@1']['output'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly email: CodecTypes['mongo/string@1']['output'];
      readonly bio: CodecTypes['mongo/string@1']['output'] | null;
      readonly role: 'admin' | 'author' | 'reader';
      readonly address: AddressOutput | null;
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Article: { readonly summary: CodecTypes['mongo/string@1']['input'] };
    readonly Post: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly title: CodecTypes['mongo/string@1']['input'];
      readonly content: CodecTypes['mongo/string@1']['input'];
      readonly kind: CodecTypes['mongo/string@1']['input'];
      readonly authorId: CodecTypes['mongo/objectId@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly Tutorial: {
      readonly difficulty: CodecTypes['mongo/string@1']['input'];
      readonly duration: CodecTypes['mongo/int32@1']['input'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly email: CodecTypes['mongo/string@1']['input'];
      readonly bio: CodecTypes['mongo/string@1']['input'] | null;
      readonly role: 'admin' | 'author' | 'reader';
      readonly address: AddressInput | null;
    };
  };
};
export type TypeMaps = MongoTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'mongo-database';
        readonly entries: {
          readonly collection: {
            readonly posts: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'authorId'; readonly direction: 1 }];
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'createdAt'; readonly direction: -1 },
                    { readonly field: 'authorId'; readonly direction: 1 },
                  ];
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'summary'; readonly direction: 1 }];
                  readonly unique: true;
                  readonly partialFilterExpression: { readonly kind: 'article' };
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly title: { readonly bsonType: 'string' };
                    readonly content: { readonly bsonType: 'string' };
                    readonly kind: { readonly bsonType: 'string' };
                    readonly authorId: { readonly bsonType: 'objectId' };
                    readonly createdAt: { readonly bsonType: 'date' };
                  };
                  readonly required: readonly [
                    '_id',
                    'authorId',
                    'content',
                    'createdAt',
                    'kind',
                    'title',
                  ];
                  readonly oneOf: readonly [
                    {
                      readonly properties: {
                        readonly _id: { readonly bsonType: 'objectId' };
                        readonly title: { readonly bsonType: 'string' };
                        readonly content: { readonly bsonType: 'string' };
                        readonly kind: { readonly enum: readonly ['article'] };
                        readonly authorId: { readonly bsonType: 'objectId' };
                        readonly createdAt: { readonly bsonType: 'date' };
                        readonly summary: { readonly bsonType: 'string' };
                      };
                      readonly required: readonly ['kind', 'summary'];
                      readonly additionalProperties: false;
                    },
                    {
                      readonly properties: {
                        readonly _id: { readonly bsonType: 'objectId' };
                        readonly title: { readonly bsonType: 'string' };
                        readonly content: { readonly bsonType: 'string' };
                        readonly kind: { readonly enum: readonly ['tutorial'] };
                        readonly authorId: { readonly bsonType: 'objectId' };
                        readonly createdAt: { readonly bsonType: 'date' };
                        readonly difficulty: { readonly bsonType: 'string' };
                        readonly duration: { readonly bsonType: 'int' };
                      };
                      readonly required: readonly ['difficulty', 'duration', 'kind'];
                      readonly additionalProperties: false;
                    },
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly users: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly email: { readonly bsonType: 'string' };
                    readonly bio: { readonly bsonType: readonly ['null', 'string'] };
                    readonly role: {
                      readonly bsonType: 'string';
                      readonly enum: readonly ['admin', 'author', 'reader'];
                    };
                    readonly address: {
                      readonly oneOf: readonly [
                        { readonly bsonType: 'null' },
                        {
                          readonly bsonType: 'object';
                          readonly properties: {
                            readonly street: { readonly bsonType: 'string' };
                            readonly city: { readonly bsonType: 'string' };
                            readonly zip: { readonly bsonType: readonly ['null', 'string'] };
                            readonly country: { readonly bsonType: 'string' };
                          };
                          readonly additionalProperties: false;
                          readonly required: readonly ['city', 'country', 'street'];
                        },
                      ];
                    };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'email', 'name', 'role'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly users: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
    readonly posts: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Post' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Article: {
            readonly fields: {
              readonly summary: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'posts' };
            readonly base: {
              readonly namespace: '__unbound__' & NamespaceId;
              readonly model: 'Post';
            };
          };
          readonly Post: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly content: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly kind: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly authorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly author: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['authorId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'posts' };
            readonly discriminator: { readonly field: 'kind' };
            readonly variants: {
              readonly Article: { readonly value: 'article' };
              readonly Tutorial: { readonly value: 'tutorial' };
            };
          };
          readonly Tutorial: {
            readonly fields: {
              readonly difficulty: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly duration: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'posts' };
            readonly base: {
              readonly namespace: '__unbound__' & NamespaceId;
              readonly model: 'Post';
            };
          };
          readonly User: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly bio: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly address: {
                readonly nullable: true;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'Address' };
              };
            };
            readonly relations: {
              readonly posts: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Post';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['authorId'];
                };
              };
            };
            readonly storage: { readonly collection: 'users' };
          };
        };
        readonly valueObjects: {
          readonly Address: {
            readonly fields: {
              readonly street: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly city: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly zip: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly country: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
          };
        };
        readonly enum: {
          readonly UserRole: {
            readonly codecId: 'mongo/string@1';
            readonly members: readonly [
              { readonly name: 'Admin'; readonly value: 'admin' },
              { readonly name: 'Author'; readonly value: 'author' },
              { readonly name: 'Reader'; readonly value: 'reader' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {};
  readonly extensions: {};
  readonly meta: {};
  readonly valueObjects: {
    readonly Address: {
      readonly fields: {
        readonly street: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly city: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly zip: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly country: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
  };
  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
