import { FileMap } from '../generateClient'

const generatedCodePreamble = `
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file
`

/**
 * To ensure it is clear that this is generated code and shall not be lint checked.
 */
export function addPreambleToJSFiles(fileMap: FileMap) {
  for (const [key, value] of Object.entries(fileMap)) {
    if (typeof value === 'string' && (key.endsWith('.js') || key.endsWith('.mjs'))) {
      fileMap[key] = addPreamble(value)
    } else if (typeof value === 'object' && value !== null) {
      addPreambleToJSFiles(value)
    }
  }
}

export function addPreamble(fileContent: string) {
  return generatedCodePreamble + fileContent
}
