// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma-next/target-postgres/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'7291093cc59a8f9401652a170628b4208ea9c0048b179543f6af8a37afa51595'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly TelemetryEvent: {
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly ingestedAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly installationId: CodecTypes['pg/text@1']['output'];
      readonly version: CodecTypes['pg/text@1']['output'];
      readonly command: CodecTypes['pg/text@1']['output'];
      readonly flags: CodecTypes['pg/jsonb@1']['output'];
      readonly runtimeName: CodecTypes['pg/text@1']['output'];
      readonly runtimeVersion: CodecTypes['pg/text@1']['output'];
      readonly os: CodecTypes['pg/text@1']['output'];
      readonly arch: CodecTypes['pg/text@1']['output'];
      readonly packageManager: CodecTypes['pg/text@1']['output'] | null;
      readonly databaseTarget: CodecTypes['pg/text@1']['output'] | null;
      readonly tsVersion: CodecTypes['pg/text@1']['output'] | null;
      readonly agent: CodecTypes['pg/text@1']['output'] | null;
      readonly extensions: CodecTypes['pg/jsonb@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly TelemetryEvent: {
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly ingestedAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly installationId: CodecTypes['pg/text@1']['input'];
      readonly version: CodecTypes['pg/text@1']['input'];
      readonly command: CodecTypes['pg/text@1']['input'];
      readonly flags: CodecTypes['pg/jsonb@1']['input'];
      readonly runtimeName: CodecTypes['pg/text@1']['input'];
      readonly runtimeVersion: CodecTypes['pg/text@1']['input'];
      readonly os: CodecTypes['pg/text@1']['input'];
      readonly arch: CodecTypes['pg/text@1']['input'];
      readonly packageManager: CodecTypes['pg/text@1']['input'] | null;
      readonly databaseTarget: CodecTypes['pg/text@1']['input'] | null;
      readonly tsVersion: CodecTypes['pg/text@1']['input'] | null;
      readonly agent: CodecTypes['pg/text@1']['input'] | null;
      readonly extensions: CodecTypes['pg/jsonb@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly telemetry_event: {
      readonly agent: CodecTypes['pg/text@1']['output'] | null;
      readonly arch: CodecTypes['pg/text@1']['output'];
      readonly command: CodecTypes['pg/text@1']['output'];
      readonly databaseTarget: CodecTypes['pg/text@1']['output'] | null;
      readonly extensions: CodecTypes['pg/jsonb@1']['output'];
      readonly flags: CodecTypes['pg/jsonb@1']['output'];
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly ingestedAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly installationId: CodecTypes['pg/text@1']['output'];
      readonly os: CodecTypes['pg/text@1']['output'];
      readonly packageManager: CodecTypes['pg/text@1']['output'] | null;
      readonly runtimeName: CodecTypes['pg/text@1']['output'];
      readonly runtimeVersion: CodecTypes['pg/text@1']['output'];
      readonly tsVersion: CodecTypes['pg/text@1']['output'] | null;
      readonly version: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly telemetry_event: {
      readonly agent: CodecTypes['pg/text@1']['input'] | null;
      readonly arch: CodecTypes['pg/text@1']['input'];
      readonly command: CodecTypes['pg/text@1']['input'];
      readonly databaseTarget: CodecTypes['pg/text@1']['input'] | null;
      readonly extensions: CodecTypes['pg/jsonb@1']['input'];
      readonly flags: CodecTypes['pg/jsonb@1']['input'];
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly ingestedAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly installationId: CodecTypes['pg/text@1']['input'];
      readonly os: CodecTypes['pg/text@1']['input'];
      readonly packageManager: CodecTypes['pg/text@1']['input'] | null;
      readonly runtimeName: CodecTypes['pg/text@1']['input'];
      readonly runtimeVersion: CodecTypes['pg/text@1']['input'];
      readonly tsVersion: CodecTypes['pg/text@1']['input'] | null;
      readonly version: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly telemetry_event: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly ingestedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly installationId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly version: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly command: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly flags: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
                readonly runtimeName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly runtimeVersion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly os: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly arch: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly packageManager: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly databaseTarget: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly tsVersion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly agent: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly extensions: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'telemetry_event_ingestedAt_idx_272db6ba';
                  readonly prefix: 'telemetry_event_ingestedAt_idx';
                  readonly columns: readonly ['ingestedAt'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly telemetry_event: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'TelemetryEvent';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly TelemetryEvent: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly ingestedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly installationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly version: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly command: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly flags: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly runtimeName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly runtimeVersion: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly os: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly arch: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly packageManager: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly databaseTarget: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tsVersion: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly agent: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly extensions: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'telemetry_event';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly ingestedAt: { readonly column: 'ingestedAt' };
                readonly installationId: { readonly column: 'installationId' };
                readonly version: { readonly column: 'version' };
                readonly command: { readonly column: 'command' };
                readonly flags: { readonly column: 'flags' };
                readonly runtimeName: { readonly column: 'runtimeName' };
                readonly runtimeVersion: { readonly column: 'runtimeVersion' };
                readonly os: { readonly column: 'os' };
                readonly arch: { readonly column: 'arch' };
                readonly packageManager: { readonly column: 'packageManager' };
                readonly databaseTarget: { readonly column: 'databaseTarget' };
                readonly tsVersion: { readonly column: 'tsVersion' };
                readonly agent: { readonly column: 'agent' };
                readonly extensions: { readonly column: 'extensions' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
