import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'

import { defaultTestConfig } from '@prisma/config'
import stripAnsi from 'strip-ansi'
import { afterEach, beforeEach, describe, expect, test, vi } from 'vitest'

import { Bootstrap } from '../bootstrap/Bootstrap'
import { Init } from '../Init'
import { Link } from '../postgres/link/Link'
import type { CliDistributionIdentity } from '../utils/cli-distribution-identity'

const { mockAddDependencies, mockAddDevDependencies, mockSdkClient } = vi.hoisted(() => ({
  mockAddDependencies: vi.fn(() => Promise.resolve()),
  mockAddDevDependencies: vi.fn(() => Promise.resolve()),
  mockSdkClient: {
    GET: vi.fn(),
    POST: vi.fn(),
  },
}))

vi.mock('@prisma/management-api-sdk', () => {
  class AuthErrorMock extends Error {
    name = 'AuthError'

    constructor(
      message: string,
      public readonly refreshTokenInvalid = false,
    ) {
      super(message)
    }
  }

  return {
    createManagementApiClient: vi.fn(() => mockSdkClient),
    AuthError: AuthErrorMock,
  }
})

vi.mock('../management-api/auth', () => ({
  login: vi.fn(() => Promise.resolve()),
}))

vi.mock('../management-api/auth-client', () => ({
  createAuthenticatedManagementAPI: vi.fn(() => ({ client: mockSdkClient })),
}))

vi.mock('../management-api/token-storage', () => ({
  FileTokenStorage: class {
    getTokens() {
      return Promise.resolve({ accessToken: 'stored_token', workspaceId: 'wksp_1' })
    }
  },
}))

vi.mock('@inquirer/prompts', () => ({
  confirm: vi.fn(),
  input: vi.fn(),
  select: vi.fn(),
}))

vi.mock('checkpoint-client', () => ({
  getSignature: vi.fn(() => Promise.resolve('test-signature-123')),
}))

vi.mock('../Generate', () => ({
  Generate: {
    new: () => ({
      parse: vi.fn(() => Promise.resolve('Generated Prisma Client')),
    }),
  },
}))

vi.mock('@prisma/migrate', () => ({
  MigrateDev: {
    new: () => ({
      parse: vi.fn(() => Promise.resolve('Migration completed')),
    }),
  },
  DbSeed: {
    new: () => ({
      parse: vi.fn(() => Promise.resolve('Seed completed')),
    }),
  },
}))

vi.mock('../init/skill-install', () => ({
  installSkills: vi.fn(() => Promise.resolve({ ok: true })),
}))

vi.mock('ora', () => ({
  default: vi.fn(() => {
    const spinner = {
      start: vi.fn(),
      succeed: vi.fn(),
      fail: vi.fn(),
    }

    spinner.start.mockReturnValue(spinner)
    return spinner
  }),
}))

vi.mock('../bootstrap/template-scaffold', () => ({
  addDependencies: mockAddDependencies,
  addDevDependencies: mockAddDevDependencies,
  detectPackageManager: vi.fn(() => 'npm'),
  downloadAndExtractTemplate: vi.fn(() => Promise.resolve()),
  installDependencies: vi.fn(() => Promise.resolve()),
  isValidTemplateName: vi.fn(() => true),
  promptTemplateSelection: vi.fn(() => Promise.resolve('nextjs')),
}))

const prismaConfigByIdentity = {
  prisma: `// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
`,
  prisma7: `// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma7 dotenv
import "dotenv/config";
import { defineConfig } from "prisma7/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
`,
} satisfies Record<CliDistributionIdentity, string>

let originalCwd: string
let tmpDir: string

beforeEach(() => {
  originalCwd = process.cwd()
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'prisma-project-creation-identity-'))
  process.chdir(tmpDir)
  mockSdkClient.GET.mockReset()
  mockSdkClient.POST.mockReset()
  mockAddDependencies.mockClear()
  mockAddDevDependencies.mockClear()
  vi.clearAllMocks()
})

afterEach(() => {
  process.chdir(originalCwd)
  vi.unstubAllEnvs()
  fs.rmSync(tmpDir, { recursive: true, force: true })
})

function render(output: string | Error): string {
  return stripAnsi(output instanceof Error ? output.message : output)
}

function setupLinkApiSuccess() {
  mockSdkClient.POST.mockResolvedValueOnce({
    data: {
      data: {
        id: 'conn_test',
        name: `dev-${os.hostname()}`,
        endpoints: {
          pooled: { connectionString: 'postgres://user:pass@db-pool.prisma.io:5432/postgres' },
          direct: { connectionString: 'postgres://user:pass@db.prisma.io:5432/postgres' },
        },
      },
    },
    error: undefined,
  })
}

function setupPpgInitApiSuccess() {
  mockSdkClient.GET.mockResolvedValueOnce({
    data: {
      data: [{ id: 'us-east-1', name: 'US East', status: 'available' }],
    },
    error: undefined,
  })

  mockSdkClient.POST.mockResolvedValueOnce({
    data: {
      data: {
        id: 'proj_compat',
        workspace: { id: 'wksp_workspace' },
        database: {
          id: 'db_environment',
          connections: [
            {
              endpoints: {
                direct: { connectionString: 'postgres://user:pass@db.prisma.io:5432/postgres' },
              },
            },
          ],
        },
      },
    },
    error: undefined,
  })
}

describe.each([
  { identity: 'prisma' as const, otherIdentity: 'prisma7' },
  { identity: 'prisma7' as const, otherIdentity: 'prisma' },
])('project creation output uses $identity', ({ identity, otherIdentity }) => {
  test('init writes the selected config import and next-step commands', async () => {
    const output = render(
      await Init.new(identity).parse(['--datasource-provider', 'postgresql', '--no-skills'], defaultTestConfig()),
    )

    const config = fs.readFileSync(path.join(tmpDir, 'prisma.config.ts'), 'utf-8')

    expect(config).toBe(prismaConfigByIdentity[identity])
    expect(output).toContain(`Local: npx ${identity} dev`)
    expect(output).toContain(`run ${identity} migrate dev`)
    expect(output).not.toContain(`Local: npx ${otherIdentity} dev`)
    expect(output).not.toContain(`run ${otherIdentity} migrate dev`)
  })

  test('prisma postgres init output keeps stable packages but switches executable guidance', async () => {
    const prismaDir = path.join(tmpDir, 'prisma')
    fs.mkdirSync(prismaDir, { recursive: true })
    fs.writeFileSync(path.join(prismaDir, 'schema.prisma'), 'datasource db { provider = "postgresql" }', 'utf-8')

    setupPpgInitApiSuccess()

    const output = render(
      await Init.new(identity).parse(
        ['--db', '--region', 'us-east-1', '--name', 'Compat Project', '--no-skills'],
        defaultTestConfig(),
      ),
    )

    expect(output).toContain('npm install @prisma/adapter-pg')
    expect(output).toContain(`npx ${identity} migrate dev`)
    expect(output).toContain(`npx ${identity} studio`)
    expect(output).not.toContain(`npx ${otherIdentity} migrate dev`)
    expect(output).not.toContain(`npx ${otherIdentity} studio`)
  })

  test('bootstrap pending dependency guidance installs and re-runs the selected package', async () => {
    fs.writeFileSync(path.join(tmpDir, 'package.json'), '{"name":"compat-project"}', 'utf-8')
    const prismaDir = path.join(tmpDir, 'prisma')
    fs.mkdirSync(prismaDir, { recursive: true })
    fs.writeFileSync(
      path.join(prismaDir, 'schema.prisma'),
      'datasource db { provider = "postgresql" }\nmodel User { id Int @id }',
      'utf-8',
    )

    const { confirm } = await import('@inquirer/prompts')
    vi.mocked(confirm).mockResolvedValue(false)

    setupLinkApiSuccess()

    const output = render(
      await Bootstrap.new(identity).parse(
        ['--api-key', 'test_key', '--database', 'db_abc123'],
        defaultTestConfig(),
        tmpDir,
      ),
    )

    expect(output).toContain(`Install @prisma/client, dotenv, and ${identity} with your package manager`)
    expect(output).toContain(`Re-run npx ${identity}@latest bootstrap`)
    expect(output).not.toContain(`Install @prisma/client, dotenv, and ${otherIdentity} with your package manager`)
    expect(output).not.toContain(`Re-run npx ${otherIdentity}@latest bootstrap`)
  })

  test('bootstrap completion guidance keeps stable paths and switches executable guidance', async () => {
    fs.writeFileSync(path.join(tmpDir, 'package.json'), '{"name":"compat-project"}', 'utf-8')
    const prismaDir = path.join(tmpDir, 'prisma')
    fs.mkdirSync(prismaDir, { recursive: true })
    fs.writeFileSync(path.join(prismaDir, 'schema.prisma'), 'datasource db { provider = "postgresql" }', 'utf-8')
    fs.mkdirSync(path.join(tmpDir, 'node_modules', 'dotenv'), { recursive: true })
    fs.mkdirSync(path.join(tmpDir, 'node_modules', identity), { recursive: true })
    fs.mkdirSync(path.join(tmpDir, 'node_modules', '@prisma', 'client'), { recursive: true })

    setupLinkApiSuccess()

    const output = render(
      await Bootstrap.new(identity).parse(
        ['--api-key', 'test_key', '--database', 'db_abc123'],
        defaultTestConfig(),
        tmpDir,
      ),
    )

    expect(output).toContain('Define your data model in prisma/schema.prisma')
    expect(output).toContain(`Run ${identity} migrate dev`)
    expect(output).toContain(`Run ${identity} studio`)
    expect(output).not.toContain(`Run ${otherIdentity} migrate dev`)
    expect(output).not.toContain(`Run ${otherIdentity} studio`)
  })

  test('postgres link completion guidance switches executable guidance only', async () => {
    const prismaDir = path.join(tmpDir, 'prisma')
    fs.mkdirSync(prismaDir, { recursive: true })
    fs.writeFileSync(
      path.join(prismaDir, 'schema.prisma'),
      'datasource db { provider = "postgresql" }\nmodel User { id Int @id @default(autoincrement()) }',
      'utf-8',
    )

    setupLinkApiSuccess()

    const output = render(
      await Link.new(identity).parse(['--api-key', 'test_key', '--database', 'db_abc123'], defaultTestConfig(), tmpDir),
    )

    expect(output).toContain(`Run ${identity} generate`)
    expect(output).toContain(`Run ${identity} migrate dev`)
    expect(output).not.toContain(`Run ${otherIdentity} generate`)
    expect(output).not.toContain(`Run ${otherIdentity} migrate dev`)
  })
})
