// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as MongoCodecTypes, Vector } from '@prisma/orm-mongo/adapter/codec-types';

import type {
  MongoCollection,
  MongoContractWithTypeMaps,
  MongoTypeMaps,
  RelationKeys,
} from '@prisma/orm-mongo/family-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-mongo/contract/types';

export type StorageHash =
  StorageHashBase<'6969147309c36a2e1cef69c2077abfa7ddb568d171ad99f03506d9f428b0a595'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'251b3ce23f6c9f561892e7c1af9d2cc941a13d64ba1aa7226b90036b09568cc3'>;

export type CodecTypes = MongoCodecTypes;

export type PriceOutput = {
  readonly amount: CodecTypes['mongo/double@1']['output'];
  readonly currency: CodecTypes['mongo/string@1']['output'];
};
export type PriceInput = {
  readonly amount: CodecTypes['mongo/double@1']['input'];
  readonly currency: CodecTypes['mongo/string@1']['input'];
};
export type ImageOutput = { readonly url: CodecTypes['mongo/string@1']['output'] };
export type ImageInput = { readonly url: CodecTypes['mongo/string@1']['input'] };
export type AddressOutput = {
  readonly streetAndNumber: CodecTypes['mongo/string@1']['output'];
  readonly city: CodecTypes['mongo/string@1']['output'];
  readonly postalCode: CodecTypes['mongo/string@1']['output'];
  readonly country: CodecTypes['mongo/string@1']['output'];
};
export type AddressInput = {
  readonly streetAndNumber: CodecTypes['mongo/string@1']['input'];
  readonly city: CodecTypes['mongo/string@1']['input'];
  readonly postalCode: CodecTypes['mongo/string@1']['input'];
  readonly country: CodecTypes['mongo/string@1']['input'];
};
export type CartItemOutput = {
  readonly productId: CodecTypes['mongo/string@1']['output'];
  readonly name: CodecTypes['mongo/string@1']['output'];
  readonly brand: CodecTypes['mongo/string@1']['output'];
  readonly amount: CodecTypes['mongo/int32@1']['output'];
  readonly price: PriceOutput;
  readonly image: ImageOutput;
};
export type CartItemInput = {
  readonly productId: CodecTypes['mongo/string@1']['input'];
  readonly name: CodecTypes['mongo/string@1']['input'];
  readonly brand: CodecTypes['mongo/string@1']['input'];
  readonly amount: CodecTypes['mongo/int32@1']['input'];
  readonly price: PriceInput;
  readonly image: ImageInput;
};
export type OrderLineItemOutput = {
  readonly productId: CodecTypes['mongo/string@1']['output'];
  readonly name: CodecTypes['mongo/string@1']['output'];
  readonly brand: CodecTypes['mongo/string@1']['output'];
  readonly amount: CodecTypes['mongo/int32@1']['output'];
  readonly price: PriceOutput;
  readonly image: ImageOutput;
};
export type OrderLineItemInput = {
  readonly productId: CodecTypes['mongo/string@1']['input'];
  readonly name: CodecTypes['mongo/string@1']['input'];
  readonly brand: CodecTypes['mongo/string@1']['input'];
  readonly amount: CodecTypes['mongo/int32@1']['input'];
  readonly price: PriceInput;
  readonly image: ImageInput;
};
export type StatusEntryOutput = {
  readonly status: CodecTypes['mongo/string@1']['output'];
  readonly timestamp: CodecTypes['mongo/date@1']['output'];
};
export type StatusEntryInput = {
  readonly status: CodecTypes['mongo/string@1']['input'];
  readonly timestamp: CodecTypes['mongo/date@1']['input'];
};
export type InvoiceLineItemOutput = {
  readonly name: CodecTypes['mongo/string@1']['output'];
  readonly amount: CodecTypes['mongo/int32@1']['output'];
  readonly unitPrice: CodecTypes['mongo/double@1']['output'];
  readonly lineTotal: CodecTypes['mongo/double@1']['output'];
};
export type InvoiceLineItemInput = {
  readonly name: CodecTypes['mongo/string@1']['input'];
  readonly amount: CodecTypes['mongo/int32@1']['input'];
  readonly unitPrice: CodecTypes['mongo/double@1']['input'];
  readonly lineTotal: CodecTypes['mongo/double@1']['input'];
};
export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly AddToCartEvent: {
      readonly productId: CodecTypes['mongo/string@1']['output'];
      readonly brand: CodecTypes['mongo/string@1']['output'];
    };
    readonly Cart: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly userId: CodecTypes['mongo/objectId@1']['output'];
      readonly items: ReadonlyArray<CartItemOutput>;
    };
    readonly Event: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly userId: CodecTypes['mongo/string@1']['output'];
      readonly sessionId: CodecTypes['mongo/string@1']['output'];
      readonly type: CodecTypes['mongo/string@1']['output'];
      readonly timestamp: CodecTypes['mongo/date@1']['output'];
    };
    readonly Invoice: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly orderId: CodecTypes['mongo/objectId@1']['output'];
      readonly items: ReadonlyArray<InvoiceLineItemOutput>;
      readonly subtotal: CodecTypes['mongo/double@1']['output'];
      readonly tax: CodecTypes['mongo/double@1']['output'];
      readonly total: CodecTypes['mongo/double@1']['output'];
      readonly issuedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly Location: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly streetAndNumber: CodecTypes['mongo/string@1']['output'];
      readonly city: CodecTypes['mongo/string@1']['output'];
      readonly postalCode: CodecTypes['mongo/string@1']['output'];
      readonly country: CodecTypes['mongo/string@1']['output'];
    };
    readonly Order: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly userId: CodecTypes['mongo/objectId@1']['output'];
      readonly items: ReadonlyArray<OrderLineItemOutput>;
      readonly shippingAddress: CodecTypes['mongo/string@1']['output'];
      readonly type: CodecTypes['mongo/string@1']['output'];
      readonly statusHistory: ReadonlyArray<StatusEntryOutput>;
    };
    readonly Product: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly brand: CodecTypes['mongo/string@1']['output'];
      readonly code: CodecTypes['mongo/string@1']['output'];
      readonly description: CodecTypes['mongo/string@1']['output'];
      readonly primaryCategory: CodecTypes['mongo/string@1']['output'];
      readonly subCategory: CodecTypes['mongo/string@1']['output'];
      readonly articleType: CodecTypes['mongo/string@1']['output'];
      readonly price: PriceOutput;
      readonly image: ImageOutput;
    };
    readonly SearchEvent: { readonly query: CodecTypes['mongo/string@1']['output'] };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly email: CodecTypes['mongo/string@1']['output'];
      readonly address: AddressOutput | null;
    };
    readonly ViewProductEvent: {
      readonly productId: CodecTypes['mongo/string@1']['output'];
      readonly subCategory: CodecTypes['mongo/string@1']['output'];
      readonly brand: CodecTypes['mongo/string@1']['output'];
      readonly exitMethod: CodecTypes['mongo/string@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly AddToCartEvent: {
      readonly productId: CodecTypes['mongo/string@1']['input'];
      readonly brand: CodecTypes['mongo/string@1']['input'];
    };
    readonly Cart: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly userId: CodecTypes['mongo/objectId@1']['input'];
      readonly items: ReadonlyArray<CartItemInput>;
    };
    readonly Event: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly userId: CodecTypes['mongo/string@1']['input'];
      readonly sessionId: CodecTypes['mongo/string@1']['input'];
      readonly type: CodecTypes['mongo/string@1']['input'];
      readonly timestamp: CodecTypes['mongo/date@1']['input'];
    };
    readonly Invoice: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly orderId: CodecTypes['mongo/objectId@1']['input'];
      readonly items: ReadonlyArray<InvoiceLineItemInput>;
      readonly subtotal: CodecTypes['mongo/double@1']['input'];
      readonly tax: CodecTypes['mongo/double@1']['input'];
      readonly total: CodecTypes['mongo/double@1']['input'];
      readonly issuedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly Location: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly streetAndNumber: CodecTypes['mongo/string@1']['input'];
      readonly city: CodecTypes['mongo/string@1']['input'];
      readonly postalCode: CodecTypes['mongo/string@1']['input'];
      readonly country: CodecTypes['mongo/string@1']['input'];
    };
    readonly Order: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly userId: CodecTypes['mongo/objectId@1']['input'];
      readonly items: ReadonlyArray<OrderLineItemInput>;
      readonly shippingAddress: CodecTypes['mongo/string@1']['input'];
      readonly type: CodecTypes['mongo/string@1']['input'];
      readonly statusHistory: ReadonlyArray<StatusEntryInput>;
    };
    readonly Product: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly brand: CodecTypes['mongo/string@1']['input'];
      readonly code: CodecTypes['mongo/string@1']['input'];
      readonly description: CodecTypes['mongo/string@1']['input'];
      readonly primaryCategory: CodecTypes['mongo/string@1']['input'];
      readonly subCategory: CodecTypes['mongo/string@1']['input'];
      readonly articleType: CodecTypes['mongo/string@1']['input'];
      readonly price: PriceInput;
      readonly image: ImageInput;
    };
    readonly SearchEvent: { readonly query: CodecTypes['mongo/string@1']['input'] };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly email: CodecTypes['mongo/string@1']['input'];
      readonly address: AddressInput | null;
    };
    readonly ViewProductEvent: {
      readonly productId: CodecTypes['mongo/string@1']['input'];
      readonly subCategory: CodecTypes['mongo/string@1']['input'];
      readonly brand: CodecTypes['mongo/string@1']['input'];
      readonly exitMethod: CodecTypes['mongo/string@1']['input'] | null;
    };
  };
};
export type TypeMaps = MongoTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'mongo-database';
        readonly entries: {
          readonly collection: {
            readonly carts: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'userId'; readonly direction: 1 }];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly userId: { readonly bsonType: 'objectId' };
                    readonly items: {
                      readonly bsonType: 'array';
                      readonly items: {
                        readonly bsonType: 'object';
                        readonly properties: {
                          readonly productId: { readonly bsonType: 'string' };
                          readonly name: { readonly bsonType: 'string' };
                          readonly brand: { readonly bsonType: 'string' };
                          readonly amount: { readonly bsonType: 'int' };
                          readonly price: {
                            readonly bsonType: 'object';
                            readonly properties: {
                              readonly amount: { readonly bsonType: 'double' };
                              readonly currency: { readonly bsonType: 'string' };
                            };
                            readonly additionalProperties: false;
                            readonly required: readonly ['amount', 'currency'];
                          };
                          readonly image: {
                            readonly bsonType: 'object';
                            readonly properties: { readonly url: { readonly bsonType: 'string' } };
                            readonly additionalProperties: false;
                            readonly required: readonly ['url'];
                          };
                        };
                        readonly additionalProperties: false;
                        readonly required: readonly [
                          'amount',
                          'brand',
                          'image',
                          'name',
                          'price',
                          'productId',
                        ];
                      };
                    };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'items', 'userId'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly events: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'userId'; readonly direction: 1 },
                    { readonly field: 'timestamp'; readonly direction: -1 },
                  ];
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'timestamp'; readonly direction: 1 }];
                  readonly expireAfterSeconds: 7776000;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly userId: { readonly bsonType: 'string' };
                    readonly sessionId: { readonly bsonType: 'string' };
                    readonly type: { readonly bsonType: 'string' };
                    readonly timestamp: { readonly bsonType: 'date' };
                  };
                  readonly required: readonly ['_id', 'sessionId', 'timestamp', 'type', 'userId'];
                  readonly oneOf: readonly [
                    {
                      readonly properties: {
                        readonly _id: { readonly bsonType: 'objectId' };
                        readonly userId: { readonly bsonType: 'string' };
                        readonly sessionId: { readonly bsonType: 'string' };
                        readonly type: { readonly enum: readonly ['view-product'] };
                        readonly timestamp: { readonly bsonType: 'date' };
                        readonly productId: { readonly bsonType: 'string' };
                        readonly subCategory: { readonly bsonType: 'string' };
                        readonly brand: { readonly bsonType: 'string' };
                        readonly exitMethod: { readonly bsonType: readonly ['null', 'string'] };
                      };
                      readonly required: readonly ['brand', 'productId', 'subCategory', 'type'];
                      readonly additionalProperties: false;
                    },
                    {
                      readonly properties: {
                        readonly _id: { readonly bsonType: 'objectId' };
                        readonly userId: { readonly bsonType: 'string' };
                        readonly sessionId: { readonly bsonType: 'string' };
                        readonly type: { readonly enum: readonly ['search'] };
                        readonly timestamp: { readonly bsonType: 'date' };
                        readonly query: { readonly bsonType: 'string' };
                      };
                      readonly required: readonly ['query', 'type'];
                      readonly additionalProperties: false;
                    },
                    {
                      readonly properties: {
                        readonly _id: { readonly bsonType: 'objectId' };
                        readonly userId: { readonly bsonType: 'string' };
                        readonly sessionId: { readonly bsonType: 'string' };
                        readonly type: { readonly enum: readonly ['add-to-cart'] };
                        readonly timestamp: { readonly bsonType: 'date' };
                        readonly productId: { readonly bsonType: 'string' };
                        readonly brand: { readonly bsonType: 'string' };
                      };
                      readonly required: readonly ['brand', 'productId', 'type'];
                      readonly additionalProperties: false;
                    },
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly invoices: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'orderId'; readonly direction: 1 }];
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'issuedAt'; readonly direction: -1 }];
                  readonly sparse: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly orderId: { readonly bsonType: 'objectId' };
                    readonly items: {
                      readonly bsonType: 'array';
                      readonly items: {
                        readonly bsonType: 'object';
                        readonly properties: {
                          readonly name: { readonly bsonType: 'string' };
                          readonly amount: { readonly bsonType: 'int' };
                          readonly unitPrice: { readonly bsonType: 'double' };
                          readonly lineTotal: { readonly bsonType: 'double' };
                        };
                        readonly additionalProperties: false;
                        readonly required: readonly ['amount', 'lineTotal', 'name', 'unitPrice'];
                      };
                    };
                    readonly subtotal: { readonly bsonType: 'double' };
                    readonly tax: { readonly bsonType: 'double' };
                    readonly total: { readonly bsonType: 'double' };
                    readonly issuedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'issuedAt',
                    'items',
                    'orderId',
                    'subtotal',
                    'tax',
                    'total',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly locations: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'city'; readonly direction: 1 },
                    { readonly field: 'country'; readonly direction: 1 },
                  ];
                  readonly collation: { readonly locale: 'en'; readonly strength: 2 };
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly streetAndNumber: { readonly bsonType: 'string' };
                    readonly city: { readonly bsonType: 'string' };
                    readonly postalCode: { readonly bsonType: 'string' };
                    readonly country: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'city',
                    'country',
                    'name',
                    'postalCode',
                    'streetAndNumber',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly orders: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'userId'; readonly direction: 1 }];
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly userId: { readonly bsonType: 'objectId' };
                    readonly items: {
                      readonly bsonType: 'array';
                      readonly items: {
                        readonly bsonType: 'object';
                        readonly properties: {
                          readonly productId: { readonly bsonType: 'string' };
                          readonly name: { readonly bsonType: 'string' };
                          readonly brand: { readonly bsonType: 'string' };
                          readonly amount: { readonly bsonType: 'int' };
                          readonly price: {
                            readonly bsonType: 'object';
                            readonly properties: {
                              readonly amount: { readonly bsonType: 'double' };
                              readonly currency: { readonly bsonType: 'string' };
                            };
                            readonly additionalProperties: false;
                            readonly required: readonly ['amount', 'currency'];
                          };
                          readonly image: {
                            readonly bsonType: 'object';
                            readonly properties: { readonly url: { readonly bsonType: 'string' } };
                            readonly additionalProperties: false;
                            readonly required: readonly ['url'];
                          };
                        };
                        readonly additionalProperties: false;
                        readonly required: readonly [
                          'amount',
                          'brand',
                          'image',
                          'name',
                          'price',
                          'productId',
                        ];
                      };
                    };
                    readonly shippingAddress: { readonly bsonType: 'string' };
                    readonly type: { readonly bsonType: 'string' };
                    readonly statusHistory: {
                      readonly bsonType: 'array';
                      readonly items: {
                        readonly bsonType: 'object';
                        readonly properties: {
                          readonly status: { readonly bsonType: 'string' };
                          readonly timestamp: { readonly bsonType: 'date' };
                        };
                        readonly additionalProperties: false;
                        readonly required: readonly ['status', 'timestamp'];
                      };
                    };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'items',
                    'shippingAddress',
                    'statusHistory',
                    'type',
                    'userId',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly products: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'name'; readonly direction: 'text' },
                    { readonly field: 'description'; readonly direction: 'text' },
                  ];
                  readonly weights: { readonly name: 10; readonly description: 1 };
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'brand'; readonly direction: 1 },
                    { readonly field: 'subCategory'; readonly direction: 1 },
                  ];
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'code'; readonly direction: 'hashed' },
                  ];
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly brand: { readonly bsonType: 'string' };
                    readonly code: { readonly bsonType: 'string' };
                    readonly description: { readonly bsonType: 'string' };
                    readonly primaryCategory: { readonly bsonType: 'string' };
                    readonly subCategory: { readonly bsonType: 'string' };
                    readonly articleType: { readonly bsonType: 'string' };
                    readonly price: {
                      readonly bsonType: 'object';
                      readonly properties: {
                        readonly amount: { readonly bsonType: 'double' };
                        readonly currency: { readonly bsonType: 'string' };
                      };
                      readonly additionalProperties: false;
                      readonly required: readonly ['amount', 'currency'];
                    };
                    readonly image: {
                      readonly bsonType: 'object';
                      readonly properties: { readonly url: { readonly bsonType: 'string' } };
                      readonly additionalProperties: false;
                      readonly required: readonly ['url'];
                    };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'articleType',
                    'brand',
                    'code',
                    'description',
                    'image',
                    'name',
                    'price',
                    'primaryCategory',
                    'subCategory',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly users: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'email'; readonly direction: 1 }];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly email: { readonly bsonType: 'string' };
                    readonly address: {
                      readonly oneOf: readonly [
                        { readonly bsonType: 'null' },
                        {
                          readonly bsonType: 'object';
                          readonly properties: {
                            readonly streetAndNumber: { readonly bsonType: 'string' };
                            readonly city: { readonly bsonType: 'string' };
                            readonly postalCode: { readonly bsonType: 'string' };
                            readonly country: { readonly bsonType: 'string' };
                          };
                          readonly additionalProperties: false;
                          readonly required: readonly [
                            'city',
                            'country',
                            'postalCode',
                            'streetAndNumber',
                          ];
                        },
                      ];
                    };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'email', 'name'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly products: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Product';
    };
    readonly users: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
    readonly carts: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Cart' };
    readonly orders: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Order' };
    readonly locations: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Location';
    };
    readonly invoices: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Invoice';
    };
    readonly events: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Event' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly AddToCartEvent: {
            readonly fields: {
              readonly productId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly brand: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'events' };
            readonly base: {
              readonly namespace: '__unbound__' & NamespaceId;
              readonly model: 'Event';
            };
          };
          readonly Cart: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly items: {
                readonly nullable: false;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'CartItem' };
                readonly many: true;
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'carts' };
          };
          readonly Event: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly sessionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly timestamp: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'events' };
            readonly discriminator: { readonly field: 'type' };
            readonly variants: {
              readonly ViewProductEvent: { readonly value: 'view-product' };
              readonly SearchEvent: { readonly value: 'search' };
              readonly AddToCartEvent: { readonly value: 'add-to-cart' };
            };
          };
          readonly Invoice: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly orderId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly items: {
                readonly nullable: false;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'InvoiceLineItem' };
                readonly many: true;
              };
              readonly subtotal: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
              };
              readonly tax: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
              };
              readonly total: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
              };
              readonly issuedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly order: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Order';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['orderId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'invoices' };
          };
          readonly Location: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly streetAndNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly city: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly postalCode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly country: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'locations' };
          };
          readonly Order: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly items: {
                readonly nullable: false;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'OrderLineItem' };
                readonly many: true;
              };
              readonly shippingAddress: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly statusHistory: {
                readonly nullable: false;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'StatusEntry' };
                readonly many: true;
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly invoices: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Invoice';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['orderId'];
                };
              };
            };
            readonly storage: { readonly collection: 'orders' };
          };
          readonly Product: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly brand: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly code: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly primaryCategory: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly subCategory: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly articleType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly price: {
                readonly nullable: false;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'Price' };
              };
              readonly image: {
                readonly nullable: false;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'Image' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'products' };
          };
          readonly SearchEvent: {
            readonly fields: {
              readonly query: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'events' };
            readonly base: {
              readonly namespace: '__unbound__' & NamespaceId;
              readonly model: 'Event';
            };
          };
          readonly User: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly address: {
                readonly nullable: true;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'Address' };
              };
            };
            readonly relations: {
              readonly carts: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Cart';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly orders: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Order';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: { readonly collection: 'users' };
          };
          readonly ViewProductEvent: {
            readonly fields: {
              readonly productId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly subCategory: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly brand: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly exitMethod: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'events' };
            readonly base: {
              readonly namespace: '__unbound__' & NamespaceId;
              readonly model: 'Event';
            };
          };
        };
        readonly valueObjects: {
          readonly Price: {
            readonly fields: {
              readonly amount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
              };
              readonly currency: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
          };
          readonly Image: {
            readonly fields: {
              readonly url: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
          };
          readonly Address: {
            readonly fields: {
              readonly streetAndNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly city: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly postalCode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly country: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
          };
          readonly CartItem: {
            readonly fields: {
              readonly productId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly brand: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly amount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly price: {
                readonly nullable: false;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'Price' };
              };
              readonly image: {
                readonly nullable: false;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'Image' };
              };
            };
          };
          readonly OrderLineItem: {
            readonly fields: {
              readonly productId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly brand: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly amount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly price: {
                readonly nullable: false;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'Price' };
              };
              readonly image: {
                readonly nullable: false;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'Image' };
              };
            };
          };
          readonly StatusEntry: {
            readonly fields: {
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly timestamp: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
          };
          readonly InvoiceLineItem: {
            readonly fields: {
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly amount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly unitPrice: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
              };
              readonly lineTotal: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {};
  readonly extensions: {};
  readonly meta: {};
  readonly valueObjects: {
    readonly Price: {
      readonly fields: {
        readonly amount: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
        readonly currency: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
    readonly Image: {
      readonly fields: {
        readonly url: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
    readonly Address: {
      readonly fields: {
        readonly streetAndNumber: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly city: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly postalCode: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly country: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
    readonly CartItem: {
      readonly fields: {
        readonly productId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly brand: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly amount: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
        };
        readonly price: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Price' };
        };
        readonly image: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Image' };
        };
      };
    };
    readonly OrderLineItem: {
      readonly fields: {
        readonly productId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly brand: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly amount: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
        };
        readonly price: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Price' };
        };
        readonly image: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Image' };
        };
      };
    };
    readonly StatusEntry: {
      readonly fields: {
        readonly status: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly timestamp: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
      };
    };
    readonly InvoiceLineItem: {
      readonly fields: {
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly amount: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
        };
        readonly unitPrice: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
        readonly lineTotal: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
      };
    };
  };
  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;

export namespace Models {
  export type unbound_Product = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    name: CodecTypes['mongo/string@1']['output'];
    brand: CodecTypes['mongo/string@1']['output'];
    code: CodecTypes['mongo/string@1']['output'];
    description: CodecTypes['mongo/string@1']['output'];
    primaryCategory: CodecTypes['mongo/string@1']['output'];
    subCategory: CodecTypes['mongo/string@1']['output'];
    articleType: CodecTypes['mongo/string@1']['output'];
    price: PriceOutput;
    image: ImageOutput;
    readonly [RelationKeys]?: never;
  };
  export type unbound_User = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    name: CodecTypes['mongo/string@1']['output'];
    email: CodecTypes['mongo/string@1']['output'];
    address: AddressOutput | null;
    carts: unbound_Cart[];
    orders: unbound_Order[];
    readonly [RelationKeys]?: 'carts' | 'orders';
  };
  export type unbound_Cart = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    userId: CodecTypes['mongo/objectId@1']['output'];
    items: ReadonlyArray<CartItemOutput>;
    user: unbound_User | null;
    readonly [RelationKeys]?: 'user';
  };
  export type unbound_Order = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    userId: CodecTypes['mongo/objectId@1']['output'];
    items: ReadonlyArray<OrderLineItemOutput>;
    shippingAddress: CodecTypes['mongo/string@1']['output'];
    type: CodecTypes['mongo/string@1']['output'];
    statusHistory: ReadonlyArray<StatusEntryOutput>;
    user: unbound_User | null;
    invoices: unbound_Invoice[];
    readonly [RelationKeys]?: 'user' | 'invoices';
  };
  export type unbound_Location = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    name: CodecTypes['mongo/string@1']['output'];
    streetAndNumber: CodecTypes['mongo/string@1']['output'];
    city: CodecTypes['mongo/string@1']['output'];
    postalCode: CodecTypes['mongo/string@1']['output'];
    country: CodecTypes['mongo/string@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type unbound_Invoice = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    orderId: CodecTypes['mongo/objectId@1']['output'];
    items: ReadonlyArray<InvoiceLineItemOutput>;
    subtotal: CodecTypes['mongo/double@1']['output'];
    tax: CodecTypes['mongo/double@1']['output'];
    total: CodecTypes['mongo/double@1']['output'];
    issuedAt: CodecTypes['mongo/date@1']['output'];
    order: unbound_Order | null;
    readonly [RelationKeys]?: 'order';
  };
  export type unbound_Event = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    userId: CodecTypes['mongo/string@1']['output'];
    sessionId: CodecTypes['mongo/string@1']['output'];
    type: 'view-product' | 'search' | 'add-to-cart';
    timestamp: CodecTypes['mongo/date@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type unbound_ViewProductEvent = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    userId: CodecTypes['mongo/string@1']['output'];
    sessionId: CodecTypes['mongo/string@1']['output'];
    type: 'view-product';
    timestamp: CodecTypes['mongo/date@1']['output'];
    productId: CodecTypes['mongo/string@1']['output'];
    subCategory: CodecTypes['mongo/string@1']['output'];
    brand: CodecTypes['mongo/string@1']['output'];
    exitMethod: CodecTypes['mongo/string@1']['output'] | null;
    readonly [RelationKeys]?: never;
  };
  export type unbound_SearchEvent = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    userId: CodecTypes['mongo/string@1']['output'];
    sessionId: CodecTypes['mongo/string@1']['output'];
    type: 'search';
    timestamp: CodecTypes['mongo/date@1']['output'];
    query: CodecTypes['mongo/string@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type unbound_AddToCartEvent = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    userId: CodecTypes['mongo/string@1']['output'];
    sessionId: CodecTypes['mongo/string@1']['output'];
    type: 'add-to-cart';
    timestamp: CodecTypes['mongo/date@1']['output'];
    productId: CodecTypes['mongo/string@1']['output'];
    brand: CodecTypes['mongo/string@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type unbound_AnyEvent =
    unbound_ViewProductEvent | unbound_SearchEvent | unbound_AddToCartEvent;
}

export declare const models: {
  __unbound__: {
    Product: Models.unbound_Product;
    User: Models.unbound_User;
    Cart: Models.unbound_Cart;
    Order: Models.unbound_Order;
    Location: Models.unbound_Location;
    Invoice: Models.unbound_Invoice;
    Event: Models.unbound_Event;
    ViewProductEvent: Models.unbound_ViewProductEvent;
    SearchEvent: Models.unbound_SearchEvent;
    AddToCartEvent: Models.unbound_AddToCartEvent;
    AnyEvent: Models.unbound_AnyEvent;
  };
};
