import { DMMF } from './dmmf-types'

export const dmmfDocument: DMMF.Document = {
  datamodel: {
    models: [
      {
        name: 'User',
        isEmbedded: false,
        isEnum: false,
        dbName: '',
        fields: [
          {
            kind: 'scalar',
            name: 'id',
            isUnique: true,
            isId: true,
            type: 'ID',
            isList: false,
            isRequired: true,
          },
          {
            kind: 'scalar',
            name: 'name',
            isUnique: false,
            isId: false,
            type: 'String',
            isList: false,
            isRequired: true,
          },
          {
            kind: 'scalar',
            name: 'strings',
            isUnique: false,
            isId: false,
            type: 'String',
            isList: true,
            isRequired: false,
          },
          {
            kind: 'relation',
            name: 'posts',
            isUnique: false,
            isId: false,
            type: 'Post',
            isList: true,
            isRequired: false,
          },
        ],
      },
      {
        name: 'Post',
        isEmbedded: false,
        isEnum: false,
        dbName: '',
        fields: [
          {
            kind: 'scalar',
            name: 'id',
            isUnique: true,
            isId: true,
            type: 'ID',
            isList: false,
            isRequired: true,
          },
          {
            kind: 'scalar',
            name: 'title',
            isUnique: false,
            isId: false,
            type: 'String',
            isList: false,
            isRequired: true,
          },
          {
            kind: 'scalar',
            name: 'content',
            isUnique: false,
            isId: false,
            type: 'String',
            isList: false,
            isRequired: true,
          },
          {
            kind: 'relation',
            name: 'author',
            isUnique: false,
            isId: false,
            type: 'User',
            isList: false,
            isRequired: true,
          },
        ],
      },
    ],
  },
  schema: {
    queries: [
      {
        name: 'users',
        args: [
          {
            name: 'where',
            type: 'UserWhereInput',
            isRequired: false,
            isScalar: false,
            isList: false,
          },
          {
            name: 'orderBy',
            type: 'UserOrderByInput',
            isRequired: false,
            isScalar: false,
            isList: false,
          },
          {
            name: 'skip',
            type: 'Int',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
          {
            name: 'after',
            type: 'String',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
          {
            name: 'before',
            type: 'String',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
          {
            name: 'first',
            type: 'Int',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
          {
            name: 'last',
            type: 'Int',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
        ],
        output: {
          name: 'User',
          isList: true,
          isRequired: true,
        },
      },
      {
        name: 'posts',
        args: [
          {
            name: 'where',
            type: 'PostWhereInput',
            isRequired: false,
            isScalar: false,
            isList: false,
          },
          {
            name: 'orderBy',
            type: 'PostOrderByInput',
            isRequired: false,
            isScalar: false,
            isList: false,
          },
          {
            name: 'skip',
            type: 'Int',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
          {
            name: 'after',
            type: 'String',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
          {
            name: 'before',
            type: 'String',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
          {
            name: 'first',
            type: 'Int',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
          {
            name: 'last',
            type: 'Int',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
        ],
        output: {
          name: 'Post',
          isList: true,
          isRequired: true,
        },
      },
      {
        name: 'user',
        args: [
          {
            name: 'where',
            type: 'UserWhereUniqueInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
        ],
        output: {
          name: 'User',
          isList: false,
          isRequired: false,
        },
      },
      {
        name: 'post',
        args: [
          {
            name: 'where',
            type: 'PostWhereUniqueInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
        ],
        output: {
          name: 'Post',
          isList: false,
          isRequired: false,
        },
      },
      {
        name: 'usersConnection',
        args: [
          {
            name: 'where',
            type: 'UserWhereInput',
            isRequired: false,
            isScalar: false,
            isList: false,
          },
          {
            name: 'orderBy',
            type: 'UserOrderByInput',
            isRequired: false,
            isScalar: false,
            isList: false,
          },
          {
            name: 'skip',
            type: 'Int',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
          {
            name: 'after',
            type: 'String',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
          {
            name: 'before',
            type: 'String',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
          {
            name: 'first',
            type: 'Int',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
          {
            name: 'last',
            type: 'Int',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
        ],
        output: {
          name: 'UserConnection',
          isList: false,
          isRequired: true,
        },
      },
      {
        name: 'postsConnection',
        args: [
          {
            name: 'where',
            type: 'PostWhereInput',
            isRequired: false,
            isScalar: false,
            isList: false,
          },
          {
            name: 'orderBy',
            type: 'PostOrderByInput',
            isRequired: false,
            isScalar: false,
            isList: false,
          },
          {
            name: 'skip',
            type: 'Int',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
          {
            name: 'after',
            type: 'String',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
          {
            name: 'before',
            type: 'String',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
          {
            name: 'first',
            type: 'Int',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
          {
            name: 'last',
            type: 'Int',
            isRequired: false,
            isScalar: true,
            isList: false,
          },
        ],
        output: {
          name: 'PostConnection',
          isList: false,
          isRequired: true,
        },
      },
      {
        name: 'node',
        args: [
          {
            name: 'id',
            type: 'ID',
            isRequired: true,
            isScalar: true,
            isList: false,
          },
        ],
        output: {
          name: 'Node',
          isList: false,
          isRequired: false,
        },
      },
    ],
    mutations: [
      {
        name: 'createUser',
        args: [
          {
            name: 'data',
            type: 'UserCreateInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
        ],
        output: {
          name: 'User',
          isList: false,
          isRequired: true,
        },
      },
      {
        name: 'createPost',
        args: [
          {
            name: 'data',
            type: 'PostCreateInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
        ],
        output: {
          name: 'Post',
          isList: false,
          isRequired: true,
        },
      },
      {
        name: 'updateUser',
        args: [
          {
            name: 'data',
            type: 'UserUpdateInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
          {
            name: 'where',
            type: 'UserWhereUniqueInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
        ],
        output: {
          name: 'User',
          isList: false,
          isRequired: false,
        },
      },
      {
        name: 'updatePost',
        args: [
          {
            name: 'data',
            type: 'PostUpdateInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
          {
            name: 'where',
            type: 'PostWhereUniqueInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
        ],
        output: {
          name: 'Post',
          isList: false,
          isRequired: false,
        },
      },
      {
        name: 'deleteUser',
        args: [
          {
            name: 'where',
            type: 'UserWhereUniqueInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
        ],
        output: {
          name: 'User',
          isList: false,
          isRequired: false,
        },
      },
      {
        name: 'deletePost',
        args: [
          {
            name: 'where',
            type: 'PostWhereUniqueInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
        ],
        output: {
          name: 'Post',
          isList: false,
          isRequired: false,
        },
      },
      {
        name: 'upsertUser',
        args: [
          {
            name: 'where',
            type: 'UserWhereUniqueInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
          {
            name: 'create',
            type: 'UserCreateInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
          {
            name: 'update',
            type: 'UserUpdateInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
        ],
        output: {
          name: 'User',
          isList: false,
          isRequired: true,
        },
      },
      {
        name: 'upsertPost',
        args: [
          {
            name: 'where',
            type: 'PostWhereUniqueInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
          {
            name: 'create',
            type: 'PostCreateInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
          {
            name: 'update',
            type: 'PostUpdateInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
        ],
        output: {
          name: 'Post',
          isList: false,
          isRequired: true,
        },
      },
      {
        name: 'updateManyUsers',
        args: [
          {
            name: 'data',
            type: 'UserUpdateManyMutationInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
          {
            name: 'where',
            type: 'UserWhereInput',
            isRequired: false,
            isScalar: false,
            isList: false,
          },
        ],
        output: {
          name: 'BatchPayload',
          isList: false,
          isRequired: true,
        },
      },
      {
        name: 'updateManyPosts',
        args: [
          {
            name: 'data',
            type: 'PostUpdateManyMutationInput',
            isRequired: true,
            isScalar: false,
            isList: false,
          },
          {
            name: 'where',
            type: 'PostWhereInput',
            isRequired: false,
            isScalar: false,
            isList: false,
          },
        ],
        output: {
          name: 'BatchPayload',
          isList: false,
          isRequired: true,
        },
      },
      {
        name: 'deleteManyUsers',
        args: [
          {
            name: 'where',
            type: 'UserWhereInput',
            isRequired: false,
            isScalar: false,
            isList: false,
          },
        ],
        output: {
          name: 'BatchPayload',
          isList: false,
          isRequired: true,
        },
      },
      {
        name: 'deleteManyPosts',
        args: [
          {
            name: 'where',
            type: 'PostWhereInput',
            isRequired: false,
            isScalar: false,
            isList: false,
          },
        ],
        output: {
          name: 'BatchPayload',
          isList: false,
          isRequired: true,
        },
      },
    ],
    inputTypes: [
      {
        name: 'UserWhereInput',
        args: [
          {
            name: 'AND',
            type: 'UserWhereInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'id',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_not',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_in',
            type: 'ID',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_not_in',
            type: 'ID',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_lt',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_lte',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_gt',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_gte',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_contains',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_not_contains',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_starts_with',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_not_starts_with',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_ends_with',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_not_ends_with',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'name',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'name_not',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'name_in',
            type: 'String',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'name_not_in',
            type: 'String',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'name_lt',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'name_lte',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'name_gt',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'name_gte',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'name_contains',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'name_not_contains',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'name_starts_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'name_not_starts_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'name_ends_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'name_not_ends_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'posts_some',
            type: 'PostWhereInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
        ],
      },
      {
        name: 'PostWhereInput',
        args: [
          {
            name: 'AND',
            type: 'PostWhereInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'id',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_not',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_in',
            type: 'ID',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_not_in',
            type: 'ID',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_lt',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_lte',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_gt',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_gte',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_contains',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_not_contains',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_starts_with',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_not_starts_with',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_ends_with',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_not_ends_with',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_not',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_in',
            type: 'String',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_not_in',
            type: 'String',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_lt',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_lte',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_gt',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_gte',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_contains',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_not_contains',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_starts_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_not_starts_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_ends_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_not_ends_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_not',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_in',
            type: 'String',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_not_in',
            type: 'String',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_lt',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_lte',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_gt',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_gte',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_contains',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_not_contains',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_starts_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_not_starts_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_ends_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_not_ends_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'author',
            type: 'UserWhereInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
        ],
      },
      {
        name: 'UserOrderByInput',
        args: [
          {
            name: 'id_ASC',
            type: 'UserOrderByInput',
            isRequired: false,
            isList: false,
            isScalar: true,
          },
          {
            name: 'id_DESC',
            type: 'UserOrderByInput',
            isRequired: false,
            isList: false,
            isScalar: true,
          },
          {
            name: 'name_ASC',
            type: 'UserOrderByInput',
            isRequired: false,
            isList: false,
            isScalar: true,
          },
          {
            name: 'name_DESC',
            type: 'UserOrderByInput',
            isRequired: false,
            isList: false,
            isScalar: true,
          },
        ],
      },
      {
        name: 'PostOrderByInput',
        args: [
          {
            name: 'id_ASC',
            type: 'PostOrderByInput',
            isRequired: false,
            isList: false,
            isScalar: true,
          },
          {
            name: 'id_DESC',
            type: 'PostOrderByInput',
            isRequired: false,
            isList: false,
            isScalar: true,
          },
          {
            name: 'title_ASC',
            type: 'PostOrderByInput',
            isRequired: false,
            isList: false,
            isScalar: true,
          },
          {
            name: 'title_DESC',
            type: 'PostOrderByInput',
            isRequired: false,
            isList: false,
            isScalar: true,
          },
          {
            name: 'content_ASC',
            type: 'PostOrderByInput',
            isRequired: false,
            isList: false,
            isScalar: true,
          },
          {
            name: 'content_DESC',
            type: 'PostOrderByInput',
            isRequired: false,
            isList: false,
            isScalar: true,
          },
        ],
      },
      {
        name: 'UserWhereUniqueInput',
        args: [
          {
            name: 'id',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
        ],
      },
      {
        name: 'PostWhereUniqueInput',
        args: [
          {
            name: 'id',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
        ],
      },
      {
        name: 'UserCreateInput',
        args: [
          {
            name: 'id',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'name',
            type: 'String',
            isList: false,
            isRequired: true,
            isScalar: true,
          },
          {
            name: 'strings',
            type: 'UserCreatestringsInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'posts',
            type: 'PostCreateManyWithoutAuthorInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
        ],
      },
      {
        name: 'UserCreatestringsInput',
        args: [
          {
            name: 'set',
            type: 'String',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
        ],
      },
      {
        name: 'PostCreateManyWithoutAuthorInput',
        args: [
          {
            name: 'create',
            type: 'PostCreateWithoutAuthorInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'connect',
            type: 'PostWhereUniqueInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
        ],
      },
      {
        name: 'PostCreateWithoutAuthorInput',
        args: [
          {
            name: 'id',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title',
            type: 'String',
            isList: false,
            isRequired: true,
            isScalar: true,
          },
          {
            name: 'content',
            type: 'String',
            isList: false,
            isRequired: true,
            isScalar: true,
          },
        ],
      },
      {
        name: 'PostCreateInput',
        args: [
          {
            name: 'id',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title',
            type: 'String',
            isList: false,
            isRequired: true,
            isScalar: true,
          },
          {
            name: 'content',
            type: 'String',
            isList: false,
            isRequired: true,
            isScalar: true,
          },
          {
            name: 'author',
            type: 'UserCreateOneWithoutPostsInput',
            isList: false,
            isRequired: true,
            isScalar: false,
          },
        ],
      },
      {
        name: 'UserCreateOneWithoutPostsInput',
        args: [
          {
            name: 'create',
            type: 'UserCreateWithoutPostsInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'connect',
            type: 'UserWhereUniqueInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
        ],
      },
      {
        name: 'UserCreateWithoutPostsInput',
        args: [
          {
            name: 'id',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'name',
            type: 'String',
            isList: false,
            isRequired: true,
            isScalar: true,
          },
          {
            name: 'strings',
            type: 'UserCreatestringsInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
        ],
      },
      {
        name: 'UserUpdateInput',
        args: [
          {
            name: 'name',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'strings',
            type: 'UserUpdatestringsInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'posts',
            type: 'PostUpdateManyWithoutAuthorInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
        ],
      },
      {
        name: 'UserUpdatestringsInput',
        args: [
          {
            name: 'set',
            type: 'String',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
        ],
      },
      {
        name: 'PostUpdateManyWithoutAuthorInput',
        args: [
          {
            name: 'create',
            type: 'PostCreateWithoutAuthorInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'connect',
            type: 'PostWhereUniqueInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'set',
            type: 'PostWhereUniqueInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'disconnect',
            type: 'PostWhereUniqueInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'delete',
            type: 'PostWhereUniqueInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'update',
            type: 'PostUpdateWithWhereUniqueWithoutAuthorInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'updateMany',
            type: 'PostUpdateManyWithWhereNestedInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'deleteMany',
            type: 'PostScalarWhereInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'upsert',
            type: 'PostUpsertWithWhereUniqueWithoutAuthorInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
        ],
      },
      {
        name: 'PostUpdateWithWhereUniqueWithoutAuthorInput',
        args: [
          {
            name: 'where',
            type: 'PostWhereUniqueInput',
            isList: false,
            isRequired: true,
            isScalar: false,
          },
          {
            name: 'data',
            type: 'PostUpdateWithoutAuthorDataInput',
            isList: false,
            isRequired: true,
            isScalar: false,
          },
        ],
      },
      {
        name: 'PostUpdateWithoutAuthorDataInput',
        args: [
          {
            name: 'title',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
        ],
      },
      {
        name: 'PostUpdateManyWithWhereNestedInput',
        args: [
          {
            name: 'where',
            type: 'PostScalarWhereInput',
            isList: false,
            isRequired: true,
            isScalar: false,
          },
          {
            name: 'data',
            type: 'PostUpdateManyDataInput',
            isList: false,
            isRequired: true,
            isScalar: false,
          },
        ],
      },
      {
        name: 'PostScalarWhereInput',
        args: [
          {
            name: 'AND',
            type: 'PostScalarWhereInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'OR',
            type: 'PostScalarWhereInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'NOT',
            type: 'PostScalarWhereInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'id',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_not',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_in',
            type: 'ID',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_not_in',
            type: 'ID',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_lt',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_lte',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_gt',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_gte',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_contains',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_not_contains',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_starts_with',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_not_starts_with',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_ends_with',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'id_not_ends_with',
            type: 'ID',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_not',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_in',
            type: 'String',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_not_in',
            type: 'String',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_lt',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_lte',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_gt',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_gte',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_contains',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_not_contains',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_starts_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_not_starts_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_ends_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'title_not_ends_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_not',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_in',
            type: 'String',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_not_in',
            type: 'String',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_lt',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_lte',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_gt',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_gte',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_contains',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_not_contains',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_starts_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_not_starts_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_ends_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content_not_ends_with',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
        ],
      },
      {
        name: 'PostUpdateManyDataInput',
        args: [
          {
            name: 'title',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
        ],
      },
      {
        name: 'PostUpsertWithWhereUniqueWithoutAuthorInput',
        args: [
          {
            name: 'where',
            type: 'PostWhereUniqueInput',
            isList: false,
            isRequired: true,
            isScalar: false,
          },
          {
            name: 'update',
            type: 'PostUpdateWithoutAuthorDataInput',
            isList: false,
            isRequired: true,
            isScalar: false,
          },
          {
            name: 'create',
            type: 'PostCreateWithoutAuthorInput',
            isList: false,
            isRequired: true,
            isScalar: false,
          },
        ],
      },
      {
        name: 'PostUpdateInput',
        args: [
          {
            name: 'title',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'author',
            type: 'UserUpdateOneRequiredWithoutPostsInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
        ],
      },
      {
        name: 'UserUpdateOneRequiredWithoutPostsInput',
        args: [
          {
            name: 'create',
            type: 'UserCreateWithoutPostsInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'connect',
            type: 'UserWhereUniqueInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'update',
            type: 'UserUpdateWithoutPostsDataInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'upsert',
            type: 'UserUpsertWithoutPostsInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
        ],
      },
      {
        name: 'UserUpdateWithoutPostsDataInput',
        args: [
          {
            name: 'name',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'strings',
            type: 'UserUpdatestringsInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
        ],
      },
      {
        name: 'UserUpsertWithoutPostsInput',
        args: [
          {
            name: 'update',
            type: 'UserUpdateWithoutPostsDataInput',
            isList: false,
            isRequired: true,
            isScalar: false,
          },
          {
            name: 'create',
            type: 'UserCreateWithoutPostsInput',
            isList: false,
            isRequired: true,
            isScalar: false,
          },
        ],
      },
      {
        name: 'UserUpdateManyMutationInput',
        args: [
          {
            name: 'name',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'strings',
            type: 'UserUpdatestringsInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
        ],
      },
      {
        name: 'PostUpdateManyMutationInput',
        args: [
          {
            name: 'title',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'content',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
        ],
      },
      {
        name: 'UserSubscriptionWhereInput',
        args: [
          {
            name: 'AND',
            type: 'UserSubscriptionWhereInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'mutation_in',
            type: 'MutationType',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'updatedFields_contains',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'updatedFields_contains_every',
            type: 'String',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'updatedFields_contains_some',
            type: 'String',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'node',
            type: 'UserWhereInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
        ],
      },
      {
        name: 'MutationType',
        args: [
          {
            name: 'CREATED',
            type: 'MutationType',
            isRequired: false,
            isList: false,
            isScalar: true,
          },
          {
            name: 'UPDATED',
            type: 'MutationType',
            isRequired: false,
            isList: false,
            isScalar: true,
          },
          {
            name: 'DELETED',
            type: 'MutationType',
            isRequired: false,
            isList: false,
            isScalar: true,
          },
        ],
      },
      {
        name: 'PostSubscriptionWhereInput',
        args: [
          {
            name: 'AND',
            type: 'PostSubscriptionWhereInput',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'mutation_in',
            type: 'MutationType',
            isList: true,
            isRequired: false,
            isScalar: false,
          },
          {
            name: 'updatedFields_contains',
            type: 'String',
            isList: false,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'updatedFields_contains_every',
            type: 'String',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'updatedFields_contains_some',
            type: 'String',
            isList: true,
            isRequired: false,
            isScalar: true,
          },
          {
            name: 'node',
            type: 'PostWhereInput',
            isList: false,
            isRequired: false,
            isScalar: false,
          },
        ],
      },
    ],
    outputTypes: [
      {
        name: 'Query',
        fields: [
          {
            name: 'users',
            type: 'User',
            isList: true,
            isRequired: true,
            args: [
              {
                name: 'where',
                type: 'UserWhereInput',
                isRequired: false,
                isScalar: false,
                isList: false,
              },
              {
                name: 'orderBy',
                type: 'UserOrderByInput',
                isRequired: false,
                isScalar: false,
                isList: false,
              },
              {
                name: 'skip',
                type: 'Int',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'after',
                type: 'String',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'before',
                type: 'String',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'first',
                type: 'Int',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'last',
                type: 'Int',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'posts',
            type: 'Post',
            isList: true,
            isRequired: true,
            args: [
              {
                name: 'where',
                type: 'PostWhereInput',
                isRequired: false,
                isScalar: false,
                isList: false,
              },
              {
                name: 'orderBy',
                type: 'PostOrderByInput',
                isRequired: false,
                isScalar: false,
                isList: false,
              },
              {
                name: 'skip',
                type: 'Int',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'after',
                type: 'String',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'before',
                type: 'String',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'first',
                type: 'Int',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'last',
                type: 'Int',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'user',
            type: 'User',
            isList: false,
            isRequired: false,
            args: [
              {
                name: 'where',
                type: 'UserWhereUniqueInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'post',
            type: 'Post',
            isList: false,
            isRequired: false,
            args: [
              {
                name: 'where',
                type: 'PostWhereUniqueInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'usersConnection',
            type: 'UserConnection',
            isList: false,
            isRequired: true,
            args: [
              {
                name: 'where',
                type: 'UserWhereInput',
                isRequired: false,
                isScalar: false,
                isList: false,
              },
              {
                name: 'orderBy',
                type: 'UserOrderByInput',
                isRequired: false,
                isScalar: false,
                isList: false,
              },
              {
                name: 'skip',
                type: 'Int',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'after',
                type: 'String',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'before',
                type: 'String',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'first',
                type: 'Int',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'last',
                type: 'Int',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'postsConnection',
            type: 'PostConnection',
            isList: false,
            isRequired: true,
            args: [
              {
                name: 'where',
                type: 'PostWhereInput',
                isRequired: false,
                isScalar: false,
                isList: false,
              },
              {
                name: 'orderBy',
                type: 'PostOrderByInput',
                isRequired: false,
                isScalar: false,
                isList: false,
              },
              {
                name: 'skip',
                type: 'Int',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'after',
                type: 'String',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'before',
                type: 'String',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'first',
                type: 'Int',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'last',
                type: 'Int',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'node',
            type: 'Node',
            isList: false,
            isRequired: false,
            args: [
              {
                name: 'id',
                type: 'ID',
                isRequired: true,
                isScalar: true,
                isList: false,
              },
            ],
            isScalar: false,
          },
        ],
      },
      {
        name: 'User',
        fields: [
          {
            name: 'id',
            type: 'ID',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
          {
            name: 'name',
            type: 'String',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
          {
            name: 'strings',
            type: 'String',
            isList: true,
            isRequired: true,
            args: [],
            isScalar: true,
          },
          {
            name: 'posts',
            type: 'Post',
            isList: true,
            isRequired: false,
            args: [
              {
                name: 'where',
                type: 'PostWhereInput',
                isRequired: false,
                isScalar: false,
                isList: false,
              },
              {
                name: 'orderBy',
                type: 'PostOrderByInput',
                isRequired: false,
                isScalar: false,
                isList: false,
              },
              {
                name: 'skip',
                type: 'Int',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'after',
                type: 'String',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'before',
                type: 'String',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'first',
                type: 'Int',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
              {
                name: 'last',
                type: 'Int',
                isRequired: false,
                isScalar: true,
                isList: false,
              },
            ],
            isScalar: false,
          },
        ],
      },
      {
        name: 'Post',
        fields: [
          {
            name: 'id',
            type: 'ID',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
          {
            name: 'title',
            type: 'String',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
          {
            name: 'content',
            type: 'String',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
          {
            name: 'author',
            type: 'User',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: false,
          },
        ],
      },
      {
        name: 'UserConnection',
        fields: [
          {
            name: 'pageInfo',
            type: 'PageInfo',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: false,
          },
          {
            name: 'edges',
            type: 'UserEdge',
            isList: true,
            isRequired: true,
            args: [],
            isScalar: false,
          },
          {
            name: 'aggregate',
            type: 'AggregateUser',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: false,
          },
        ],
      },
      {
        name: 'PageInfo',
        fields: [
          {
            name: 'hasNextPage',
            type: 'Boolean',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
          {
            name: 'hasPreviousPage',
            type: 'Boolean',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
          {
            name: 'startCursor',
            type: 'String',
            isList: false,
            isRequired: false,
            args: [],
            isScalar: true,
          },
          {
            name: 'endCursor',
            type: 'String',
            isList: false,
            isRequired: false,
            args: [],
            isScalar: true,
          },
        ],
      },
      {
        name: 'UserEdge',
        fields: [
          {
            name: 'node',
            type: 'User',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: false,
          },
          {
            name: 'cursor',
            type: 'String',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
        ],
      },
      {
        name: 'AggregateUser',
        fields: [
          {
            name: 'count',
            type: 'Int',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
        ],
      },
      {
        name: 'PostConnection',
        fields: [
          {
            name: 'pageInfo',
            type: 'PageInfo',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: false,
          },
          {
            name: 'edges',
            type: 'PostEdge',
            isList: true,
            isRequired: true,
            args: [],
            isScalar: false,
          },
          {
            name: 'aggregate',
            type: 'AggregatePost',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: false,
          },
        ],
      },
      {
        name: 'PostEdge',
        fields: [
          {
            name: 'node',
            type: 'Post',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: false,
          },
          {
            name: 'cursor',
            type: 'String',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
        ],
      },
      {
        name: 'AggregatePost',
        fields: [
          {
            name: 'count',
            type: 'Int',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
        ],
      },
      {
        name: 'Mutation',
        fields: [
          {
            name: 'createUser',
            type: 'User',
            isList: false,
            isRequired: true,
            args: [
              {
                name: 'data',
                type: 'UserCreateInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'createPost',
            type: 'Post',
            isList: false,
            isRequired: true,
            args: [
              {
                name: 'data',
                type: 'PostCreateInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'updateUser',
            type: 'User',
            isList: false,
            isRequired: false,
            args: [
              {
                name: 'data',
                type: 'UserUpdateInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
              {
                name: 'where',
                type: 'UserWhereUniqueInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'updatePost',
            type: 'Post',
            isList: false,
            isRequired: false,
            args: [
              {
                name: 'data',
                type: 'PostUpdateInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
              {
                name: 'where',
                type: 'PostWhereUniqueInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'deleteUser',
            type: 'User',
            isList: false,
            isRequired: false,
            args: [
              {
                name: 'where',
                type: 'UserWhereUniqueInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'deletePost',
            type: 'Post',
            isList: false,
            isRequired: false,
            args: [
              {
                name: 'where',
                type: 'PostWhereUniqueInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'upsertUser',
            type: 'User',
            isList: false,
            isRequired: true,
            args: [
              {
                name: 'where',
                type: 'UserWhereUniqueInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
              {
                name: 'create',
                type: 'UserCreateInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
              {
                name: 'update',
                type: 'UserUpdateInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'upsertPost',
            type: 'Post',
            isList: false,
            isRequired: true,
            args: [
              {
                name: 'where',
                type: 'PostWhereUniqueInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
              {
                name: 'create',
                type: 'PostCreateInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
              {
                name: 'update',
                type: 'PostUpdateInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'updateManyUsers',
            type: 'BatchPayload',
            isList: false,
            isRequired: true,
            args: [
              {
                name: 'data',
                type: 'UserUpdateManyMutationInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
              {
                name: 'where',
                type: 'UserWhereInput',
                isRequired: false,
                isScalar: false,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'updateManyPosts',
            type: 'BatchPayload',
            isList: false,
            isRequired: true,
            args: [
              {
                name: 'data',
                type: 'PostUpdateManyMutationInput',
                isRequired: true,
                isScalar: false,
                isList: false,
              },
              {
                name: 'where',
                type: 'PostWhereInput',
                isRequired: false,
                isScalar: false,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'deleteManyUsers',
            type: 'BatchPayload',
            isList: false,
            isRequired: true,
            args: [
              {
                name: 'where',
                type: 'UserWhereInput',
                isRequired: false,
                isScalar: false,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'deleteManyPosts',
            type: 'BatchPayload',
            isList: false,
            isRequired: true,
            args: [
              {
                name: 'where',
                type: 'PostWhereInput',
                isRequired: false,
                isScalar: false,
                isList: false,
              },
            ],
            isScalar: false,
          },
        ],
      },
      {
        name: 'BatchPayload',
        fields: [
          {
            name: 'count',
            type: 'Long',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
        ],
      },
      {
        name: 'Subscription',
        fields: [
          {
            name: 'user',
            type: 'UserSubscriptionPayload',
            isList: false,
            isRequired: false,
            args: [
              {
                name: 'where',
                type: 'UserSubscriptionWhereInput',
                isRequired: false,
                isScalar: false,
                isList: false,
              },
            ],
            isScalar: false,
          },
          {
            name: 'post',
            type: 'PostSubscriptionPayload',
            isList: false,
            isRequired: false,
            args: [
              {
                name: 'where',
                type: 'PostSubscriptionWhereInput',
                isRequired: false,
                isScalar: false,
                isList: false,
              },
            ],
            isScalar: false,
          },
        ],
      },
      {
        name: 'UserSubscriptionPayload',
        fields: [
          {
            name: 'mutation',
            type: 'MutationType',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: false,
          },
          {
            name: 'node',
            type: 'User',
            isList: false,
            isRequired: false,
            args: [],
            isScalar: false,
          },
          {
            name: 'updatedFields',
            type: 'String',
            isList: true,
            isRequired: false,
            args: [],
            isScalar: true,
          },
          {
            name: 'previousValues',
            type: 'UserPreviousValues',
            isList: false,
            isRequired: false,
            args: [],
            isScalar: false,
          },
        ],
      },
      {
        name: 'UserPreviousValues',
        fields: [
          {
            name: 'id',
            type: 'ID',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
          {
            name: 'name',
            type: 'String',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
          {
            name: 'strings',
            type: 'String',
            isList: true,
            isRequired: true,
            args: [],
            isScalar: true,
          },
        ],
      },
      {
        name: 'PostSubscriptionPayload',
        fields: [
          {
            name: 'mutation',
            type: 'MutationType',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: false,
          },
          {
            name: 'node',
            type: 'Post',
            isList: false,
            isRequired: false,
            args: [],
            isScalar: false,
          },
          {
            name: 'updatedFields',
            type: 'String',
            isList: true,
            isRequired: false,
            args: [],
            isScalar: true,
          },
          {
            name: 'previousValues',
            type: 'PostPreviousValues',
            isList: false,
            isRequired: false,
            args: [],
            isScalar: false,
          },
        ],
      },
      {
        name: 'PostPreviousValues',
        fields: [
          {
            name: 'id',
            type: 'ID',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
          {
            name: 'title',
            type: 'String',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
          {
            name: 'content',
            type: 'String',
            isList: false,
            isRequired: true,
            args: [],
            isScalar: true,
          },
        ],
      },
    ],
  },
  mappings: [
    {
      model: 'User',
      findOne: 'user',
      findMany: 'users',
      create: 'createUser',
      update: 'updateUser',
      updateMany: 'updateManyUser',
      upsert: 'upsertUser',
      delete: 'deleteUser',
      deleteMany: 'deleteManyUser',
    },
    {
      model: 'Post',
      findOne: 'post',
      findMany: 'posts',
      create: 'createPost',
      update: 'updatePost',
      updateMany: 'updateManyPost',
      upsert: 'upsertPost',
      delete: 'deletePost',
      deleteMany: 'deleteManyPost',
    },
  ],
}
