import { defineConfig } from '@prisma-next/tsdown';

export default defineConfig({
  entry: [
    'src/exports/codec-ids.ts',
    'src/exports/codec-types.ts',
    'src/exports/codec-descriptor.ts',
    'src/exports/codecs.ts',
    'src/exports/control.ts',
    'src/exports/contract-free.ts',
    'src/exports/data-transform.ts',
    'src/exports/ddl.ts',
    'src/exports/default-normalizer.ts',
    'src/exports/diff-database-schema.ts',
    'src/exports/errors.ts',
    'src/exports/issue-planner.ts',
    'src/exports/migration.ts',
    'src/exports/native-type-normalizer.ts',
    'src/exports/op-factory-call.ts',
    'src/exports/pack.ts',
    'src/exports/planner-ddl-builders.ts',
    'src/exports/planner-identity-values.ts',
    'src/exports/planner-produced-postgres-migration.ts',
    'src/exports/planner-schema-lookup.ts',
    'src/exports/planner-sql-checks.ts',
    'src/exports/planner-target-details.ts',
    'src/exports/planner.ts',
    'src/exports/render-ops.ts',
    'src/exports/render-typescript.ts',
    'src/exports/rls-canonicalize.ts',
    'src/exports/runtime.ts',
    'src/exports/schema-ir-annotations.ts',
    'src/exports/sql-utils.ts',
    'src/exports/types.ts',
  ],
});
