import { FileMap } from '../generateClient'

const generatedCodePreamble = `
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
`

/**
 * To ensure it is clear that this is generated code and shall not be lint checked.
 */
export function addPreambleToTSFiles(fileMap: FileMap) {
  for (const [key, value] of Object.entries(fileMap)) {
    if (typeof value === 'string' && key.endsWith('.ts')) {
      fileMap[key] = generatedCodePreamble + value
    } else if (typeof value === 'object' && value !== null) {
      addPreambleToTSFiles(value)
    }
  }
}
