name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18', '20', '22', '24']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install & build
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
          skip-tsc: false
          skip-build: false
