name: Bundle size

on:
  pull_request:
    paths-ignore:
      # Any update here needs to be done for all files
      # (test.yml, benchmark.yml, release.yml, bundle-size.yml, ci-aux-files.yml)
      - '*.md'
      - '*.bench.ts'
      - 'LICENSE'
      - '.dockerignore'
      - 'scripts/ci/publish.ts'
      - '.github/CODEOWNERS'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/DISCUSSION_TEMPLATE/**'
      - '.devcontainer/**'
      - '.vscode/**'
      - 'graphs/**'
      - 'sandbox/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  size:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install & build
        uses: ./.github/actions/setup
        with:
          node-version: '20.19.0'
          skip-tsc: true
          skip-build: true

      - uses: andresz1/size-limit-action@e7493a72a44b113341c0cf6186ab49c17c4b65c1 # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: bundle-size
