name: Daily BuildPulse run

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru - “At every 30th minute past every hour from 3 through 4.”
    - cron: '*/30 3-4 * * *'

jobs:
  run_tests:
    uses: ./.github/workflows/test-template.yml
    with:
      reason: buildpulse
      jobTimeout: 70
    secrets: inherit
