name: Lint GitHub Actions workflows
on:
  pull_request:
    paths:
      - '.github/**'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      # see https://github.com/rhysd/actionlint/blob/main/docs/usage.md
      - name: Check workflow files
        # https://hub.docker.com/r/rhysd/actionlint/tags
        uses: docker://rhysd/actionlint:1.7.1
