name: npm - manage dist tag
run-name: npm - manage dist tag / ${{ github.event.inputs.tagAction}} ${{ github.event.inputs.tagName}} (on ${{ github.event.inputs.targetVersion}})

on:
  workflow_dispatch:
    inputs:
      tagAction:
        description: 'What action do you want to do with the tag?'
        type: choice
        options:
          - 'add'
          - 'rm'
        required: true
      tagName:
        description: 'What is the name of the dist tag to be managed (created/updated or deleted)?'
        type: string
        required: true
      targetVersion:
        description: 'Version to act on (Only needed with `add` in format of semver version to tag, otherwise empty).'
        type: string
        required: false

jobs:
  manage_tag:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        env:
          THE_INPUT: '${{ toJson(github.event.inputs) }}'
        run: |
          echo "$THE_INPUT"

      - uses: actions/checkout@v4

      - name: Check if version is valid
        if: ${{ github.event.inputs.tagAction == 'add' }}
        run: |
          npm show "prisma${{ env.VERSION }}" version
        env:
          VERSION: ${{ github.event.inputs.targetVersion && format('@{0}', github.event.inputs.targetVersion) || '' }}

      - name: Create or delete npm tag
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc

          echo "The following commands will be executed, for example:"
          echo "npm dist-tag '${{ env.ACTION }}' '@prisma/client${{ env.VERSION }}' '${{ env.TAG_NAME }}'"

          sleep 10

          npm dist-tag "${{ env.ACTION }}" "@prisma/client${{ env.VERSION }}" "${{ env.TAG_NAME }}"
          npm dist-tag "${{ env.ACTION }}" "prisma${{ env.VERSION }}" "${{ env.TAG_NAME }}"

          npm dist-tag "${{ env.ACTION }}" "@prisma/adapter-d1${{ env.VERSION }}" "${{ env.TAG_NAME }}"

        env:
          # Secrets
          # Note: must use personal access token
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Used by the script
          VERSION: ${{ github.event.inputs.targetVersion && format('@{0}', github.event.inputs.targetVersion) || '' }}
          ACTION: ${{ github.event.inputs.tagAction }}
          TAG_NAME: ${{ github.event.inputs.tagName }}
