name: npm - create dist tag
run-name: npm - run `npm dist-tag ${{ github.event.inputs.tagAction }} ${{ github.event.inputs.targetPackage }} ${{ github.event.inputs.tagName }}`

on:
  workflow_dispatch:
    inputs:
      tagAction:
        description: 'What do you want to do with the tag?'
        type: choice
        options:
          - 'add'
          - 'rm'
        required: true
      tagName:
        description: 'What is the name of the dist tag to be managed?'
        type: string
        required: true
      targetPackage:
        description: '"add" needs <package>@<version>, "rm" needs <package> only'
        type: string
        required: true

jobs:
  manage_tag:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        env:
          THE_INPUT: '${{ toJson(github.event.inputs) }}'
        run: |
          echo $THE_INPUT

      - uses: actions/checkout@v4

      - name: Create or delete tag on npm
        id: manage
        run: |
          npm dist-tag ${{ github.event.inputs.tagAction }} ${{ github.event.inputs.targetPackage }} ${{ github.event.inputs.tagName }}
        env:
          # Secrets
          # Note: must use personal access token
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
