name: npm - manage dist tag

on:
  workflow_dispatch:
    inputs:
      tagAction:
        description: 'What do you want to do with the tag?'
        type: choice
        options:
          - 'add'
          - 'rm'
        required: true
      tagName:
        description: 'What is the name of the dist tag to be managed?'
        type: string
        required: true
      targetVersion:
        description: 'Only needed when you needed to create a new tag.'
        type: string
        required: true
        default: '---'

jobs:
  manage_tag:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        env:
          THE_INPUT: '${{ toJson(github.event.inputs) }}'
        run: |
          echo $THE_INPUT

      - uses: actions/checkout@v4

      - name: Create or delete npm tag
        id: manage
        run: |
          echo "The following commands will be executed, for example:"
          echo "npm dist-tag '${{ env.ACTION }}' '@prisma/client${{ env.VERSION }}' '${{ env.TAG_NAME }}'"
          sleep 10
          npm dist-tag "${{ env.ACTION }}" "@prisma/client${{ env.VERSION }}" "${{ env.TAG_NAME }}"
          npm dist-tag "${{ env.ACTION }}" "@prisma/adapter-libsql${{ env.VERSION }}" "${{ env.TAG_NAME }}"
          npm dist-tag "${{ env.ACTION }}" "@prisma/adapter-neon${{ env.VERSION }}" "${{ env.TAG_NAME }}"
          npm dist-tag "${{ env.ACTION }}" "@prisma/adapter-pg${{ env.VERSION }}" "${{ env.TAG_NAME }}"
          npm dist-tag "${{ env.ACTION }}" "prisma${{ env.VERSION }}" "${{ env.TAG_NAME }}"
        env:
          # Secrets
          # Note: must use personal access token
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Used by the script
          VERSION: ${{ contains(github.event.inputs.version, '---') && '' || join(['@', github.event.inputs.version], '') }}
          ACTION: ${{ github.event.inputs.tagAction }}
          TAG_NAME: ${{ github.event.inputs.tagName }}
