name: npm - Release Prisma
run-name: npm - Release Prisma ${{ inputs.packageVersion }}${{ github.event.inputs.commitHash && '-' || '' }}${{ inputs.commitHash }}

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        required: true
        description: 'Target package version'
      commitHash:
        required: false
        description: 'Target commit hash'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    outputs:
      PACKAGE_VERSION: ${{ steps.package-version.outputs.PACKAGE_VERSION }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commitHash }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://npm.pkg.github.com
          scope: '@vetching-corporation'
          cache: 'pnpm'

      - name: Parse Package Version
        id: package-version
        run: |
          BASE_VERSION="${{ github.event.inputs.packageVersion }}"
          COMMIT_HASH="${{ github.event.inputs.commitHash }}"

          # 커밋 해시가 없으면 기본 버전 사용 (eg. "6.9.0")
          if [ -z "$COMMIT_HASH" ]; then
            echo "PACKAGE_VERSION=${BASE_VERSION}" >> $GITHUB_OUTPUT

          # 커밋 해시가 있으면 dev 버전 사용 (eg. "6.9.0-{sequence}.{commit-hash}")
          else
            results=$(
              curl \
                -sSfL \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github+json" \
                "https://api.github.com/orgs/vetching-corporation/packages/npm/prisma-client/versions"
            )
            SEQUENCE=$(echo "$results" | jq -r --arg base "$BASE_VERSION" '
              [.[].name                                       # 모든 tag 이름
              | select(startswith($base + "-"))               # base-prefix 필터
              | capture("^" + $base + "-(?<seq>[0-9]+)\\.")   # seq 추출
              | (.seq | tonumber)                             # 숫자로 변환
              ] | max // 0 | . + 1                            # 최대값(+1), 없으면 1
            ')

            echo "PACKAGE_VERSION=${BASE_VERSION}-${SEQUENCE}.${COMMIT_HASH}" >> $GITHUB_OUTPUT
          fi

      - name: Install jq
        uses: dcarbone/install-jq-action@v3

      - name: Set package version
        run: |
          PACKAGE_VERSION="${{ steps.package-version.outputs.PACKAGE_VERSION }}"

          CONFIG_DIR="packages/config"
          CLIENT_DIR="packages/client"
          CLI_DIR="packages/cli"

          # Config package.json
          jq --arg version "$PACKAGE_VERSION" '.version = $version' "$CONFIG_DIR/package.json" > "$CONFIG_DIR/package-temp.json"
          mv "$CONFIG_DIR/package-temp.json" "$CONFIG_DIR/package.json"

          # Client package.json
          jq --arg version "$PACKAGE_VERSION" '.version = $version' "$CLIENT_DIR/package.json" > "$CLIENT_DIR/package-temp.json"
          mv "$CLIENT_DIR/package-temp.json" "$CLIENT_DIR/package.json"

          # CLI package.json
          jq --arg version "$PACKAGE_VERSION" '.version = $version | .dependencies["@vetching-corporation/prisma-config"] = "workspace:" + $version' "$CLI_DIR/package.json" > "$CLI_DIR/package-temp.json"
          mv "$CLI_DIR/package-temp.json" "$CLI_DIR/package.json"

      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm install --lockfile-only && \
          pnpm install && \
          pnpm build

      - name: Publish all packages to npm
        id: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          (
            cd packages/config && \
            pnpm publish --no-git-checks
          )
          (
            cd packages/client && \
            pnpm publish --no-git-checks
          )
          (
            cd packages/cli && \
            pnpm publish --no-git-checks
          )

      - name: Print output
        env:
          THE_OUTPUT: '${{ toJson(steps.publish.outputs) }}'
        run: |
          echo "$THE_OUTPUT"

  # We also have `sendSlackMessage()` in publish.ts
  # It uses the #feed-prisma-releases channel and adds more information
  success:
    needs:
      - release
    if: ${{ success() }}
    name: Communicate success
    runs-on: ubuntu-latest
    steps:
      - name: Set current job url in SLACK_FOOTER env var
        run: echo "SLACK_FOOTER=<$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|Click here to go to the job logs>" >> "$GITHUB_ENV"

      - name: Slack Notification on Success
        uses: rtCamp/action-slack-notify@v2.3.2
        env:
          SLACK_TITLE: 'Prisma Release ${{ needs.release.outputs.PACKAGE_VERSION }} succeeded :white_check_mark:'
          SLACK_COLOR: '#55ff55'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

  failure:
    needs:
      - release
    if: ${{ failure() }}
    name: Communicate failure
    runs-on: ubuntu-latest
    steps:
      - name: Set current job url in SLACK_FOOTER env var
        run: echo "SLACK_FOOTER=<$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|Click here to go to the job logs>" >> "$GITHUB_ENV"

      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.3.2
        env:
          SLACK_TITLE: 'Prisma Release ${{ needs.release.outputs.PACKAGE_VERSION }} failed :x:'
          SLACK_COLOR: '#FF0000'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
